### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by rahulraj710** [smuellerDD/jitterentropy-library#114]
Hello,

I've been trying to run the jitter entropy library on Ubuntu that is installed on virtual box. 
I ran the 'make' and 'make install' command but keep getting "Segmentation fault" error when I try to run libjitterentropy.so.3.5.0 through 'sudo ./libjitterentropy.so.3.5.0'.

I've been able to run the tests and would appreciate some guidance on how to make the library itself work.

Thank you

**Comment by smuellerDD** [comment]
Am Dienstag, 7. November 2023, 21:39:20 CET schrieb rahulraj710:

Hi rahulraj710,

> Hello,
> 
> I've been trying to run the jitter entropy library on Ubuntu that is
> installed on virtual box. I ran the 'make' and 'make install' command but
> keep getting "Segmentation fault" error when I try to run
> libjitterentropy.so.3.5.0 through 'sudo ./libjitterentropy.so.3.5.0'.

I am not sure what you want to do, you want to execute a shared library? 
Perhaps a wrapping application is needed, no?
> 
> I've been able to run the tests and would appreciate some guidance on how to
> make the library itself work.
> 
> Thank you


Ciao
Stephan

**Comment by rahulraj710** [comment]
I'm basically trying to see if I can provide my own entropy source to the library but I thought I should be able to make it run first. Does that mean I need another application that uses this library? Also, is it possible to customize this library to accept a different source for entropy other than timestamps ?

**Comment by smuellerDD** [comment]
Am Mittwoch, 8. November 2023, 03:38:38 CET schrieb rahulraj710:

Hi rahulraj710,

> I'm basically trying to see if I can provide my own entropy source to the
> library but I thought I should be able to make it run first. Does that mean
> I need another application that uses this library? Also, is it possible to
> customize this library to accept a different source for entropy other than
> timestamps ?

Any library requires an application. You may use the jitterentropy-rngd.

Ciao
Stephan
