### ISSUE TITLE
SHA3 conflict with latest libressl

### ISSUE THREAD

**Issue by ronaaron** [smuellerDD/jitterentropy-library#117]
In [8th](https://8th-dev.com) I've linking with your library as well as libressl. With the latest (3.9.1) of libressl, there is a conflict with your library, around the SHA3 functions.

I fixed it locally by renaming your SHA3 functions as "jit_sha3...", but that's only a temporary solution.

I'd like to request a compile flag to disable compilation of the internal SHA3 implementation for those of use who have one already linked in.

**Comment by smuellerDD** [comment]
Am Mittwoch, 17. April 2024, 12:34:13 MESZ schrieb ronaaron:

Hi ronaaron,

> In [8th](https://8th-dev.com) I've linking with your library as well as
> libressl. With the latest (3.9.1) of libressl, there is a conflict with
> your library, around the SHA3 functions.
> 
> I fixed it locally by renaming your SHA3 functions as "jit_sha3...", but
> that's only a temporary solution.
> 
> I'd like to request a compile flag to disable compilation of the internal
> SHA3 implementation for those of use who have one already linked in.

Oh, I have never thought about using a private namespace for the Jitter RNG 
library.

I will fix that asap. The symbol names will all be jent_...

Ciao
Stephan

**Comment by ronaaron** [comment]
That's a good fix, though it would even be better if you allowed disabling the core SHA3 functions since ... well, why have them twice?

**Comment by ronaaron** [comment]
aha! OK, that makes sense, thanks.

**Comment by smuellerDD** [comment]
Change applied.
