### ISSUE TITLE
Permanent failure return codes not documented in manpage 

### ISSUE THREAD

**Issue by xnox** [smuellerDD/jitterentropy-library#118]
In 
https://github.com/smuellerDD/jitterentropy-library/blob/e0c9f55ed17728bcf475e1e6f99cc2d2bd21d0c8/doc/jitterentropy.3#L226

Return codes -1 through to -5 are documented.

Whilst -6..-8 can be returned as per https://github.com/smuellerDD/jitterentropy-library/blob/e0c9f55ed17728bcf475e1e6f99cc2d2bd21d0c8/src/jitterentropy-base.c#L167

**Comment by smuellerDD** [comment]
Update applied. Thanks for the note.

**Comment by xnox** [comment]
Patch reference https://github.com/smuellerDD/jitterentropy-library/commit/4e26649aaafcd612e0fb921ac78593a0d12febcb
