### ISSUE TITLE
Lack of "then" in the validation script

### ISSUE THREAD

**Issue by LikelyLee** [smuellerDD/jitterentropy-library#120]
In the validation script: `tests/raw-entropy/validation-runtime/processdata.sh`, there is a "then" statement missing under line 161, which makes it unable to proceed. See the picture below:

![Pasted image](https://github.com/user-attachments/assets/331cd869-f3ba-4190-8519-b553c2801366)

**Comment by smuellerDD** [comment]
Patch applied, thanks
