### ISSUE TITLE
rt library in extractlsb Makefile

### ISSUE THREAD

**Issue by jvdsn** [smuellerDD/jitterentropy-library#123]
https://github.com/smuellerDD/jitterentropy-library/blob/master/tests/raw-entropy/validation-runtime-kernel/Makefile and https://github.com/smuellerDD/jitterentropy-library/blob/master/tests/raw-entropy/validation-restart-kernel/Makefile still specify `rt` as a library to build `extractlsb`. This causes issues on platforms such as macOS where `rt` is not defined. Moreover, according to online sources, `rt` generally isn't required anymore except on very old platforms. Finally, it's unclear to me if `rt` would even be required for `extractlsb` specifically, considering that program does not use the clock anymore for any purposes. It only reads in the collected data from the kernel.

All that being said, I believe `rt` can be removed from those Makefiles?

**Comment by smuellerDD** [comment]
Am Dienstag, 1. Oktober 2024, 01:58:25 MESZ schrieb Joachim Vandersmissen:

Hi Joachim,

> All that being said, I believe `rt` can be removed from those Makefiles?

Yes. It was only added because in distant past it was required.


Ciao
Stephan
