### ISSUE TITLE
Allowing for single sample collection

### ISSUE THREAD

**Issue by VinceX** [smuellerDD/jitterentropy-library#132]
It's not an issue but in Nov. 15th update, in jitterentropy-noise.c on line 64, the variable `time` hasn't been changed to `time_now`. I tested this, undefined `JENT_CONF_DISABLE_LOOP_SHUFFLE`, and it allowed me to get my single set of sample of time deltas.

![Screenshot 2024-12-07 075415](https://github.com/user-attachments/assets/e1f734d3-46aa-46f9-9648-a908c147c81f)

**Comment by smuellerDD** [comment]
Fix applied, thanks
