### ISSUE TITLE
CPU Jitter - Windows Implementation

### ISSUE THREAD

**Issue by jlramage** [smuellerDD/jitterentropy-library#20]
Hello - Is it possible to implement CPU Jitter in a Windows OS environment e.g. Windows 10? If not at present, are there any plans to implement in Windows in the near future? Rationale would be to provide a NIST SP 800-90B compliant entropy source option in the Windows environment.
Thanks!

**Comment by smuellerDD** [comment]
Am Freitag, dem 22.01.2021 um 12:33 -0800 schrieb jlramage:
> Hello - Is it possible to implement CPU Jitter in a Windows OS environment
> e.g. Windows 10? If not at present, are there any plans to implement in
> Windows in the near future? Rationale would be to provide a NIST SP 800-90B
> compliant entropy source option in the Windows environment.
> Thanks!
> 

Sure, that is possible - the Jitter RNG even worked directly on bare metal
without any OS.

The key is to use the arch/jitterentropy-base-x86-windows.h instead of
jitterentropy-base-user.h.

Ciao
Stephan

**Comment by jlramage** [comment]
Thank you for the update Stephan! 
We will investigate and attempt to build and run CPU Jitter in Windows 10. I will close this issue.
Cheers, Jim.
