### ISSUE TITLE
[SP 800-90B] Having two distinct approaches for the timer source complicates evaluation

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#22]
When JENT_CONF_ENABLE_INTERNAL_TIMER is defined (it is by default) a pthread-based timer may be used in the event that the initial testing in jent_time_entropy_init fails.

When compiling the library, one can disable this feature by removing this define, and when this define was set in compilation, the user can force this feature using the JENT_FORCE_INTERNAL_TIMER flag when calling jent_time_entropy_init, but for a fixed architecture, one should probably be consistently using or not using this feature (depending on how course the underlying timer is).

This is probably reasonable from a defensive programming standpoint, from from a SP 800-90B assessment strategy (and presumably for any assessment scheme), it is much preferable to be able to force this internal timer feature to be used, or force the feature to not be used.

In the current implementation, if JENT_CONF_ENABLE_INTERNAL_TIMER is set, then evaluating this library must effectively occur twice, once for the internal timer, and once for the hardware timer (and the resulting entropy claim would be the lesser of the two entropies). This doubling of the assessment work would not be necessary if there was a runtime flag to force use of the underlying hardware timers (analogous to the flag to force the use of the internal timer.)

**Comment by smuellerDD** [comment]
Am Sonntag, dem 07.03.2021 um 14:14 -0800 schrieb Joshua E. Hill:
> When JENT_CONF_ENABLE_INTERNAL_TIMER is defined (it is by default) a
> pthread-based timer may be used in the event that the initial testing in
> jent_time_entropy_init fails.
> 
> When compiling the library, one can disable this feature by removing this
> define, and when this define was set in compilation, the user can force this
> feature using the JENT_FORCE_INTERNAL_TIMER flag when calling
> jent_time_entropy_init, but for a fixed architecture, one should probably be
> consistently using or not using this feature (depending on how course the
> underlying timer is).

The detection logic in the Jitter RNG code is intended to select the timer
source that is applicable to the current system. It prefers the hardware
timer, but allows the use of the software timer.

Fixing it at compile time to a certain option would imply that one compilation
(e.g. done by a distro) may work on one system as executed by user A but does
not work on another system by user B even though the respective other timer
would allow the operation on the system of user B. This seems to be an
artificial limitation that I think is against the general use of the Jitter
RNG.

> 
> This is probably reasonable from a defensive programming standpoint, from
> from a SP 800-90B assessment strategy (and presumably for any assessment
> scheme), it is much preferable to be able to force this internal timer
> feature to be used, or force the feature to not be used.

I understand that the validation work may be viewed to increase, but I
honestly do not believe that.

The validation and any possible FIPS/ENT certificates apply to one specific
hardware that was tested.

That hardware either has a high-res timer or not. It is quite unlikely that
for one given hardware system, different instances of the Jitter RNG would
pick the hardware timer once and then the software timer.

Thus it is reasonable to determine that only one timer needs to be analyzed.

> 
> In the current implementation, if JENT_CONF_ENABLE_INTERNAL_TIMER is set,
> then evaluating this library must effectively occur twice, once for the
> internal timer, and once for the hardware timer (and the resulting entropy
> claim would be the lesser of the two entropies). This doubling of the
> assessment work would not be necessary if there was a runtime flag to force
> use of the underlying hardware timers (analogous to the flag to force the
> use of the internal timer.)

For the sake of discussion, let us assume the lab has to perform the
assessment twice. About which effort do we discuss?

1. Edit the raw-entropy/recording_userspace/invoke_testing.sh to disable
FORCE_NOTIME_NOISE_SOURCE

2. Execute invoke_testing.sh - the run may take a couple of minutes and is
fully automated

3. Execute raw-entropy/validation-restart/processdata.sh which is fully
automated

4. Execute raw-entropy/validation-runtime/processdata.sh which is fully
automated

5. Verify the results of steps 3 and 4 - may be it takes 5 minutes to look at
the output

Repeat all steps again where at step 1 FORCE_NOTIME_NOISE_SOURCE is enabled.

Both rounds need to be performed for all platforms you want to cover with your
certificate. All rounds can even be executed in parallel if timing is of
essence.

So, I am not sure where the additional work is materially adding more effort
(step 5 seems to be the only manual work for the assessment by checking the
numbers). Can you please help me understand where you see significant more
work?

Thanks
Stephan

**Comment by joshuaehill** [comment]
Your description of the evaluation is how your perform the eventual statistical testing used to create H_original, and presumes that the interfaces that you identify are reasonable sources for raw data. You are ignoring any sort of machine-centric creation of a defensible H_submitter estimate, which is somewhat more time intensive.

Fundamentally, JENT_CONF_ENABLE_INTERNAL_TIMER is enabled and JENT_FORCE_INTERNAL_TIMER is not set, there is a runtime decision which clearly has the capacity to impact important behavior the source, with no external visibility as to which was chosen. That there is a substantial (machine- and environment-specific) chance that one path is chosen over the other path doesn't mean that you can ignore the other possibility.

**Comment by smuellerDD** [comment]
Am Montag, 8. März 2021, 18:03:16 CET schrieb Joshua E. Hill:

Hi Joshua,

> Your description of the evaluation is how your perform the eventual
> statistical testing used to create H_original, and presumes that the
> interfaces that you identify are reasonable sources for raw data. You are
> ignoring any sort of machine-centric creation of a defensible H_submitter
> estimate, which is somewhat more time intensive.
> 
> Fundamentally, JENT_CONF_ENABLE_INTERNAL_TIMER is enabled and
> JENT_FORCE_INTERNAL_TIMER is not set, there is a runtime decision which
> clearly has the capacity to impact important behavior the source, with no
> external visibility as to which was chosen. That there is a substantial
> (machine- and environment-specific) chance that one path is chosen over the
> other path doesn't mean that you can ignore the other possibility.

Again, if you think that you need to calculate both paths, I still do not see 
that the additional effort is significant compared to the apparent benefit it 
brings.

Ciao
Stephan

**Comment by joshuaehill** [comment]
If the end resolution here is "do nothing", I will point out that the likely end result is that vendors using this library who don't want to spend money to evaluate a mode that they don't intend to use will do one of two things:

1. If the product is on hardware with a fine-grained hardware timer, they will recompile the library after removing the `JENT_CONF_ENABLE_INTERNAL_TIMER` define. This will generally prevent them from using pre-packaged binaries, which are likely to have been compiled with `JENT_CONF_ENABLE_INTERNAL_TIMER` defined (as it is defined by default).
2. If the product is on hardware lacking a fine-grained timer, then they will leave the `JENT_CONF_ENABLE_INTERNAL_TIMER` defined, and pass in the `JENT_FORCE_INTERNAL_TIMER` flag on when invoking `rand_data *jent_entropy_collector_alloc`.

To restate: my proposal is just to add an analogous flag to force use of the hardware timer, which would make it so that vendors in situation (1) don't need to recompile the library.

**Comment by smuellerDD** [comment]
Ok, JENT_DISABLE_INTERNAL_TIMER added.
