### ISSUE TITLE
[SP 800-90B] The implemented RCT test isn't the described SP 800-90B test

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#23]
Under the assumption that your raw data is the 64-bit timer delta value, then your paper correctly describes the condition under which the RCT timer should be iterated (the second order delta is 0). This code also iterates the RCT counter when current_delta is 0 (that is, the timer did not increment between timer reads), or when the third order delta is 0. 

This makes the implemented RCT test a developer-defined health test (and not an instance of the approved health test, which is how your paper describes it). In validation, this health test must be shown to satisfy SP 800-90B Section 4.5 requirement (a) requirement (which it likely does). This variation also makes the calculated false reject rate (alpha) for this test incorrect.

**Comment by smuellerDD** [comment]
Am Sonntag, 7. März 2021, 23:23:40 CET schrieb Joshua E. Hill:

Hi Joshua,

> Under the assumption that your raw data is the 64-bit timer delta value,
> then your paper correctly describes the condition under which the RCT timer
> should be iterated (the second order delta is 0). This code also iterates
> the RCT counter when current_delta is 0 (that is, the timer did not
> increment between timer reads), or when the third order delta is 0. This
> makes your RCT a developer-defined health test, not an instance of the
> approved RCT (as described in your paper).
> 
> That said, it's trivial to show that SP 800-90B Section 4.5 requirement (a)
> is fulfilled by this test.

And that is the goal of it. The Jitter RNG code is more conservative as 90B 
requires it to be.

Ciao
Stephan

**Comment by joshuaehill** [comment]
That's fine (and your RCT implementation is clearly compliant with SP 800-90B Section 4.5 requirement a).

Mainly, this issue resulted from my insufficiently careful reading of your document. In Section 3.4.2 of your paper you are fairly explicit about this for the RCT, but in in section 7.2.43 of your paper you seem to suggest that the relevant requirements are in 90B Section 4.4, but they are instead in Section 4.5.

The stated calculation for the cutoff based on alpha is probably incorrect, and the stated alpha is likely too low for the cutoff value that you have selected (as there are more ways to fail this test than anticipated).

**Comment by smuellerDD** [comment]
I currently read in section 7.2.43:

"""
Hence, the first discrete derivative is considered to be identical to the ``approved'' RCT specified in SP800-90B section 4.4. In addition, linear and exponential patterns are identified with the first and third discrete derivative, respectively. As the additional pattern recognition do not invalidate the mandatory pattern recognition, this RCT approach therefore is considered to be an enhanced version of the ``approved'' RCT and thus meets the requirement (a) of SP800-90B section 4.5.
"""

What do you think is missing here?

**Comment by joshuaehill** [comment]
The title of the section suggests the text addresses the requirements of section 4.4, whereas the text actually addresses requirement 4.5 (a) for the RCT.

**Comment by smuellerDD** [comment]
Section title updated to point to 4.4 and 4.5. Thanks

**Comment by joshuaehill** [comment]
@smuellerDD : What is your preferred way of receiving comments on your paper "CPU Time Jitter Based Non-Physical True Random Number Generator"?

**Comment by smuellerDD** [comment]
Am Dienstag, dem 09.03.2021 um 14:07 -0800 schrieb Joshua E. Hill:

Hi Joshua,

> @smuellerDD : What is your preferred way of receiving comments on your paper
> "CPU Time Jitter Based Non-Physical True Random Number Generator"?
> 

I think email is just fine considering that I do not manage the document in
github.

Thanks
Stephan
