### ISSUE TITLE
[SP 800-90B] The library user should be able to force the fips_enabled flag

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#25]
When the fips_enabled flag is not set, the results of the APT test is never reported. This makes the setting of this flag hugely important on a variety of system that must comply to SP 800-90B, as if this flag is not set, the entropy cannot comply to the SP 800-90B requirements.

The library establishes the setting of this flag within jent_fips_enabled function from either a linked library (openssl or libgcrypt), or by looking for a leading '1' character in "/proc/sys/crypto/fips_enabled". If this file is absent or does not start with a '1', then the flag is cleared.

In standalone use, this only works when run on an OS that provides this interface (modern Linux kernels whose proc fs is mounted in the standard location?) and requires that the underlying kernel must itself be running in FIPS mode. This isn't always the case.

It seems a much easier approach to allow the user to pass in a flag requesting that the APT results actually do something.

**Comment by smuellerDD** [comment]
Am Sonntag, 7. März 2021, 23:52:45 CET schrieb Joshua E. Hill:

Hi Joshua,

> When the fips_enabled flag is not set, the results of most of the health
> testing is never reported. This makes the setting of this flag hugely
> important on a variety of system that must comply to SP 800-90B, as if this
> flag is not set, the entropy cannot comply to the SP 800-90B requirements.

Sure, that is the intention of it because not everybody wants these health 
tests.
> 
> The library establishes the setting of this flag within jent_fips_enabled
> function from either a linked library (openssl or libgcrypt), or by looking
> for a leading '1' character in "/proc/sys/crypto/fips_enabled". If this
> file is absent or does not start with a '1', then the flag is cleared.
> 
> In standalone use, this only works when run on an OS that provides this
> interface (modern Linux kernels whose proc fs is mounted in the standard
> location?)

If /proc is not there, all hell breaks loose on Linux because a large number 
of basic user space tools rely on proc being there.

> and requires that the underlying kernel must itself be running
> in FIPS mode. This isn't always the case.

If this is not the case, the user commonly does not want FIPS.
> 
> It seems a much easier approach to allow the user to pass in a flag
> requesting that the health test results actually do something.

Patch applied.


Ciao
Stephan
