### ISSUE TITLE
The test failure cutoff in jent_time_entropy_init isn't the intended cutoff

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#26]
Exchanging the order of integer multiplication and integer division can produce different results in C, so the cutoff in the code
`JENT_POWERUP_TESTLOOPCOUNT/10 * 9` (which evaluates to 918 in this codebase) is not the same as `(JENT_POWERUP_TESTLOOPCOUNT*9)/10` (which would evaluate to 921 in this codebase). The desired cutoff appears to be 90% of 1024, which is 921.6; this is closer to the second of these two.

On a related editorial note, the macro JENT_STUCK_INIT_THRES doesn't appear to be used anywhere.

**Comment by smuellerDD** [comment]
Agreed, but it is a cosmetic fix only.

Applied. Thanks.

**Comment by joshuaehill** [comment]
I agree. I don't expect that this changes much of anything. (It also doesn't have any SP 800-90B impact, which is why I dropped that flag from the issue subject). It's just something that came up in my recent review.
