### ISSUE TITLE
The use of jent_loop_shuffle obscures the underlying distribution and its contribution to entropy production isn't easy to assess.

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#28]
In its normal mode of operation, this library uses `jent_loop_shuffle` to establish a count of additional loops of hash stages in `jent_hash_time`, or additional memory access loops in `jent_memaccess`. This value is established by the current timer value on invocation (Note: not a timer delta) XORed with part of the prior conditioned output.

The prior conditioned output cannot be credited as containing entropy in this use because it was already output (and its entropy was already accounted for). That said, it is the output of SHA-3, so it is pseudorandom. Similarly, the current time at the start of the jent_loop_shuffle presumably has substantial mutual information shared with the delta value about to be generated (for the `jent_memaccess` use) and that was just generated (for the `jent_hash_time` use). As such there is probably _some_ information that is non-mutual in this new `jen_get_nstime_internal` result (and thus this parameter might have non-zero conditional entropy) , but it probably isn't very much.

The eventual raw data (the delta values used within the library) is ultimately distributed according to a parameterized family of distributions (where the parameters are the number of iterations performed within `jent_memaccess` in the current collection round and the number of hash iterations performed in the prior round) rather than a single fixed distribution.

This is all somewhat complicated, and its not clear how much actual additional entropy arises due to the use of `jent_loop_shuffle`, but there's nothing really problematic about this from a theoretical perspective. That said, these constructions make accurate entropy assessment much more complicated and laborious. Anyone performing such an assessment is forced to either identify a worst case distribution from the family (which I would generally expect to be the minimum number of loops in each case), or to test them all and take the minimum.

Notably, one _cannot_ just take the delta values generated with the library and perform statistical assessment on them, because the impact of the pseudo-random value integrated from prior output completely obscures any entropy that you actually get from the current timer value, and this pseudo randomness artificially "spreads out" the output distribution without any actual entropy contribution.

As such, when generating H_submitter for a SP 800-90B assessment, you are forced to use the second column of output from your test code; the first column is not amenable to statistical assessment because the choice of selection from which parameterized distribution is being sampled is dominated by an entropy-free but pseudorandom data value.

It would be dramatically easier to assess this source if both of these loops had a fixed number of iterations. In the event where more entropy is required, it seems more reasonable to increase these fixed loop counts.

**Comment by smuellerDD** [comment]
Am Montag, 8. März 2021, 01:54:15 CET schrieb Joshua E. Hill:

Hi Joshua,

> In its normal mode of operation, this library uses `jent_loop_shuffle` to
> establish a count of additional loops of hash stages in `jent_hash_time`,
> or additional memory access loops in `jent_memaccess`. This value is
> established by the current timer value on invocation (Note: not a timer
> delta) XORed with part of the prior conditioned output.
> 
> The prior conditioned output cannot be credited as containing entropy in
> this use because it was already output (and its entropy was already
> accounted for).

Agreed, and it is never claimed that this is a source of entropy.

> That said, this output is the output of SHA-3, so it is
> pseudorandom. Similarly, the current time at the start of the
> jent_loop_shuffle presumably has substantial mutual information shared with
> the delta value about to be generated (for the `jent_memaccess` use) and
> that was just generated (for the `jent_hash_time` use). As such there is
> probably _some_ non-mutual information (and thus some non-zero conditional
> entropy) in this new jen_get_nstime_internal result, but it probably isn't
> very much.

Well, ok. But none of that data is treated to have any entropy. All it does is 
to tell how many SHA-3 operations shall be conducted. And the timing of those 
numbers of invocations is what provides entropy.

> 
> More concerningly, the eventual raw data (the delta values used within the
> library) is ultimately distributed according to a parameterized family of
> distributions (where the parameters are the number of iterations performed
> within `jent_memaccess` in the current collection round and the number of
> hash iterations performed in the prior round) rather than a single fixed
> distribution.

Yes, that is it.
> 
> This is all somewhat complicated, and its not clear how much actual
> additional entropy arises due to the use of `jent_loop_shuffle`, but
> there's nothing really problematic about this from a theoretical
> perspective. That said, these constructions make accurate entropy
> assessment much more complicated and laborious. Anyone performing such an
> assessment is forced to either identify a worst case distribution from the
> family (which I would generally expect to be the minimum number of loops in
> each case), or to test them all and take the minimum.

This worst case is easily provided with the "single" raw test results. If you 
like to look at that, please do.

The test tool provides both views, the worst case and the "regular" case. It 
is your choice what you want to consider.

> 
> Notably, one _cannot_ just take the delta values generated with the library
> and perform statistical assessment on them, because the impact of the
> pseudo-random value integrated from prior output completely obscures any
> entropy that you actually get from the current timer value, and this pseudo
> randomness artificially "spreads out" the output distribution without any
> actual entropy contribution.
> 
> As such, when generating H_submitter for a SP 800-90B assessment, you are
> forced to use the second column of output from your test code; the first
> column is not amenable to statistical assessment because the choice of
> selection from which parameterized distribution is being sampled is
> dominated by an entropy-free but pseudorandom data value.

The tools provided give you the worst case. If you like to rest your argument 
on it, please go ahead.

Ciao
Stephan

**Comment by joshuaehill** [comment]
I certainly agree that the "minimum loop" case is almost certainly going to be the lowest entropy condition. There are bizarre theoretical issues still that could lead to dramatic reductions in entropy in other cases, but I don't expect that such a thing would be practically possible.

The main thing that I wanted to point out (which also seemed to apply to issue #21) is that statistical evaluation of the first column of your test code is very likely going to be artificially high because of the pseudo-random input integrated by `jent_loop_shuffle`.

**Comment by smuellerDD** [comment]
Am Montag, 8. März 2021, 21:44:49 CET schrieb Joshua E. Hill:

Hi Joshua,

> I certainly agree that the "minimum loop" case is almost certainly going to
> be the lowest entropy condition. There are bizarre theoretical issues still
> that could lead to dramatic reductions in entropy in other cases, but I
> don't expect that such a thing would be practically possible.
> 
> The main thing that I wanted to point out (which also seemed to apply to
> issue #21) is that statistical evaluation of the first column of your test
> code is very likely going to be artificially high because of the
> pseudo-random input integrated by `jent_loop_shuffle`.

I can see the argument and I can understand the argument. But I do not fully 
follow the argument. Also speaking to other crypto folks, they tended to agree 
with me.

Yet, I expected such concerns and thus always right from the inception of the 
Jitter RNG provide the worst case and what I consider the regular case. This I 
think should satisfy both view points as I do not want to force one or the 
other viewpoint.

Ciao
Stephan

**Comment by smuellerDD** [comment]
I would like to close the issue as the discussion continues in comment #21.
