### ISSUE TITLE
[SP 800-90B] The variable number of invocations of the conditioner make it questionable if the conditioner is a vetted conditioner

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#29]
The number of iterations of the SHA-3 primitive is not fixed; for the current code, this varies between 1 and 8 (inclusive, determined mostly pseudo randomly, but with some non-deterministic component). Notably, by FIPS 140-2 IG 7.19 Resolution 7, this entire construction cannot be described as a single vetted conditioning component.

First note that even if we fix the number of iterations at 1, we have to rely on IG7.19 resolutions #6 to describe this construction as a vetted conditioning component (as both the loop count and the prior output is included as inputs to the function).

There are several possible ways of interpreting this functionality in the language of SP 800-90B and IG7.19, and none of them yield an unambiguous and apparently durable conclusion that this conditioning is vetted.

As a general principle, in SP 800-90B, “conditioning function” is deterministic (see SP 800-90B Sections 2.2.2 and 3.1.5). The count of hashes is dependent on a non-deterministic input from jent_loop_shuffle, and the decision as to how to describe this non-deterministic input effectively establishes how this is described in this framework.

**Interpretation 1**: lfsr_loop_cnt is used to choose one of a set of parameterized conditioning functions (one for each 1 to 8 cycles of SHA-3 hashing). In this case the 2-8 iteration functions would not be vetted conditioning functions (by IG 7.19 Resolution #7). Further, it is not clear that such a non-deterministic "selection from a family on conditioning functions" is actually allowed by SP 800-90B.

**Interpretation 2**: In SP 800-90B Resolution 3, there is no specific requirement that the conditioning chain length be fixed, so it is perhaps possible to treat this as a chain of 1-8 stages of a vetted conditioning function. It is not clear if this is allowed by SP 800-90B.

**Interpretation 3**: Any prior hashing (to the extent that it exists) is only generating "supplemental data" (as per IG 7.19 Resolution #6) for the last iteration of SHA-3. This yields a single vetted conditioning function, so I guess that it's the way to go, but I'm pretty sure that this wasn't one of the anticipated uses of the "supplemental data" in IG 7.19, so it isn't clear how durable this interpretation really is.

From the perspective of SP 800-90B, it would be dramatically easier to deal with this conditioning function if the number of iterations was fixed.

**Comment by smuellerDD** [comment]
Am Montag, 8. März 2021, 02:26:34 CET schrieb Joshua E. Hill:

Hi Joshua,

> The number of iterations of the SHA-3 primitive is not fixed; for the
> current code, this varies between 1 and 8 (inclusive, determined mostly
> pseudo randomly, but with some non-deterministic component). Notably, by
> FIPS 140-2 IG 7.19 Resolution 7, this entire construction cannot be
> described as a single vetted conditioning component.
 
The Jitter RNG use one vetted conditioning component, SHA-3. It invoke it 
multiple times, yes, but it still stays as one vetted operation.

Considering the statement beneath table in 90B section 3.1.5.1.1, a vetted 
conditioning component can be treated to not loose entropy. So, a repeated 
invocation of the vetted conditioning operation will not diminish the entropy.


> First note that even if we fix the number of iterations at 1, we have to
> rely on IG7.19 resolutions #6 to describe this construction as a vetted
> conditioning component (as both the loop count and the prior output is
> included as inputs to the function).

This is exactly what the Jitter RNG does. That means that by repeating the 
conditioning operation, it still falls under the resolution 6.

If you think that this is still not valid, it is trivial to change the SHA-3 
operation to not be a self-feeding loop. With two or three lines of code 
change it would simply perform the SHA-3 operation multiple times without 
interlinking them. Irrespective of how many SHA-3 operations are performed, 
each of the SHA-3 operations results yields the same result.

So, bottom line is that SHA-3 with one loop calculates the exact same value as 
invoking SHA-3 multiple times.

The Jitter RNG does not rely on the self-feeding loop.

All that is needed is to add a sha3_init call into the loop and perform the 
sha3_final operation to generate data for the pool only in the last round.

 
> There are several possible ways of interpreting this functionality in the
> language of SP 800-90B and IG7.19, and none of them yield an unambiguous
> and apparently durable conclusion that this conditioning is vetted.
 
> As a general principle, in SP 800-90B, “conditioning function” is
> deterministic (see SP 800-90B Sections 2.2.2 and 3.1.5). The count of
> hashes is dependent on a non-deterministic input from jent_loop_shuffle,
> and the decision as to how to describe this non-deterministic input
> effectively establishes how this is described in this framework.
 
> **Interpretation 1**: lfsr_loop_cnt is used to choose one of a set of
> parameterized conditioning functions (one for each 1 to 8 cycles of SHA-3
> hashing). In this case the 2-8 iteration functions would not be vetted
> conditioning functions (by IG 7.19 Resolution #7). Further, it is not clear
> that such a non-deterministic "selection from a family on conditioning
> functions" is actually allowed by SP 800-90B.
 
> **Interpretation 2**: In SP 800-90B Resolution 3, there is no specific
> requirement that the conditioning chain length be fixed, so it is perhaps
> possible to treat this as a chain of 1-8 stages of a vetted conditioning
> function. It is not clear if this is allowed by SP 800-90B.
 
> **Interpretation 3**: Any prior hashing (to the extent that it exists) is
> only generating "supplemental data" (as per IG 7.19 Resolution #6) for the
> last iteration of SHA-3. This yields a single vetted conditioning function,
> so I guess that it's the way to go, but I'm pretty sure that this wasn't
> one of the anticipated uses of the "supplemental data" in IG 7.19, so it
> isn't clear how durable this interpretation really is.
 
> From the perspective of SP 800-90B, it would be dramatically easier to deal
> with this conditioning function if the number of iterations wasn't
> non-deterministic.
 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/smuellerDD/jitterentropy-library/issues/29


Ciao
Stephan

**Comment by joshuaehill** [comment]
One small note: If this were purely a repeated composition of SHA-3 (it is not) then there would be a (random-map-collision-induced) entropy reduction that would occur each round. You feed the `time` in at each round, so this doesn't happen here.

I think that I have a path through this even with the current functionality (interpretation 3 I mentioned above), I'm just not sure that it's likely to be a durable interpretation as the requirement set continues to evolve. The change that you suggest would seem to more durably resolve the (possible) issue.

**Comment by smuellerDD** [comment]
Patch applied to ensure that the hash operation is disentangled from the loop count - irrespective of the loop count, the hash operation always returns the same output.
