### ISSUE TITLE
[SP 800-90B] It is not easy to access raw data.

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#30]
The raw data in this library would seem to be the `current_delta` value calculated within the `jent_measure_jitter` function.

A tester can get analogous data using the helpfully provided `jitterentropy-hashtime` program in the test code, but this isn't actually the raw data for the final module. Instead, the `jitterentropy-hashtime` provides a sort of simplification of the actual noise source. I view this as a helpful tool for extracting data that can ultimately be used to support some particular H_submitter claim, but it seems dubious that CMVP/NIST would view this as a reasonable way to extract raw data from the actual entropy source. (As an aside, I know of a CST laboratory that has explicitly decided that the output of the `jitterentropy-hashtime` program **cannot** be described as raw data).

As such, it would be useful to have some sort of system in place that provides access to this data in at least some situations. Importantly, using this access method can't change the behavior of the raw data.

**Comment by smuellerDD** [comment]
I am not quite sure I follow the assessment.

I answered a similar comment on https://github.com/smuellerDD/jitterentropy-library/issues/21#issuecomment-782663785. I thought that this argument demonstrates that the hashtime tool does the exact same operations with the Jitter RNG as the Jitter RNG code itself when it calculates `current_delta`.

I understand that it may be easier to directly extract `current_delta`. But as this implies that testing interfaces need to be added to the production code, I never thought this was a wise decision. I am not against adding such interfaces per se, but I looking for a rationale why the aforementioned comment response is not sufficient.

**Comment by joshuaehill** [comment]
I understand that the test code contains all the same high level steps that are expected to significantly alter the behavior of the source, and acknowledge that `jitterentropy-hashtime` is a really good model that can be used to find H_submitter.

The CST lab's concern is that, even though `jitterentropy-hashtime` contains a clearly analogous process, it is not actually the entropy source under test, so it is not an appropriate source for the raw data. There are requirements in SP 800-90B that are relevant:

- **Section 3.1.1:** A sequential dataset of at least 1 000 000 sample values obtained directly from the noise source (i.e., raw data) shall be collected for validation.
- **Section 3.2.3, Requirement #5:** Data shall be collected from the entropy source under validation. 

To satisfy these, the CST lab needs to argue that `jitterentropy-hashtime` is an instance of the entropy source. There is a bunch of (likely not terribly relevant) logic that is missing from `jitterentropy-hashtime`, so it is hard to make this argument.

**Comment by smuellerDD** [comment]
Am Montag, 8. März 2021, 18:15:06 CET schrieb Joshua E. Hill:

Hi Joshua,

> To satisfy these, the CST lab needs to argue that `jitterentropy-hashtime`
> is an instance of the entropy source. There is a bunch of (likely not
> terribly relevant) logic that is missing from `jitterentropy-hashtime`, so
> it is hard to make this argument.

But isn't that exactly showing that the test code exhibits a strictly worst 
case by skipping a few cycles that may introduce additional entropy?

Ciao
Stephan

**Comment by joshuaehill** [comment]
I agree, and as such I think that `jitterentropy-hashtime` is a perfectly good source for data to support the creation of H_submitter. 

That said, for a raw data sample (ultimately used to generate H_original, support restart testing, etc.) 90B requires raw data from the entropy source, not raw data that is expected to be similar to what the entropy source would use.

**Comment by smuellerDD** [comment]
Patch applied to get true raw noise.
