### ISSUE TITLE
APT test reporting not enabled for ec_min in jitterentropy-hashtime

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#32]
In jitterentropy-hashtime, in [this line](https://github.com/smuellerDD/jitterentropy-library/blob/1143fcbd212363d907ef7e51da818c05f83dbcdb/tests/raw-entropy/recording_userspace/jitterentropy-hashtime.c#L79) reporting of the the 90B APT test is enabled for the ec context, but not the ec_min context.

It seems reasonable to set `ec_min->fips_enabled = 1` as well.

**Comment by smuellerDD** [comment]
Patch applied, thanks.
