### ISSUE TITLE
Running tests in user space is quite time consuming.

### ISSUE THREAD

**Issue by DK-DARKmatter** [smuellerDD/jitterentropy-library#33]
Hi there,

I just used the invoked_testing.sh to perform a test in user space. But it just stuck at lfsroutput() steps.
I receive no error message so I believe the compile step is OK, I got the executable and a process running on my machine. 
I think it is abnormal to take such a long time to perform the test, it took more than 30 minutes and it still cannot finish the first step. So I just want to make sure, how much time it will take to perform the whole test? Since I perform this task on a virtual machine, will this be the reason? If it's not, what could be the reason then?

Thanks in advance.

**Comment by smuellerDD** [comment]
Am Dienstag, dem 13.04.2021 um 02:53 -0700 schrieb Ke Zhao:
> Hi there,
> 
> I just used the invoked_testing.sh to perform a test in user space. But it
> just stuck at lfsroutput() steps.

Depending on the performance of your CPU that may take a while. The generated
data file will reach exactly 32 mil bytes before the end.

On a low-end system of mine, this may take one or two hours.

Though, considering that now the Jitter RNG has a vetted conditioning
component, the generation of this data is not strictly needed any more for 90B
compliance.

> I receive no error message so I believe the compile step is OK, I got the
> executable and a process running on my machine. 
> I think it is abnormal to take such a long time to perform the test, it took
> more than 30 minutes and it still cannot finish the first step. So I just
> want to make sure, how much time it will take to perform the whole test?
> Since I perform this task on a virtual machine, will this be the reason? If
> it's not, what could be the reason then?

Ciao
Stephan
> 
> Thanks in advance.
>

**Comment by DK-DARKmatter** [comment]
Hi Stephan,
Thanks for the reply! I restart the test and this time I got the job done. The test just simply take longer times than my imagination. But anyway, I got the result, and I am curious on how these entropy data fit with SP 800-90B. 

Again, thanks for your help!
Have a nice day.


Regards

**Comment by smuellerDD** [comment]
Am Dienstag, dem 13.04.2021 um 23:25 -0700 schrieb Ke Zhao:
> Hi Stephan,
> Thanks for the reply! I restart the test and this time I got the job done.
> The test just simply take longer times than my imagination. But anyway, I
> got the result, and I am curious on how these entropy data fit with SP 800-
> 90B. 

Use the validation tools - they generate the runtime and restart analysis
values.

Now compare the obtained values with the implicitly assumed values that is (1
/ osr) bits. If the measured value is higher than the implied value, you are
good. Otherwise the Jitter RNG is not good on your system (and you may need to
increase the osr).

Ciao
Stephan 
> 
> Again, thanks for your help!
> Have a nice day.
> 
> 
> Regards
>
