### ISSUE TITLE
[SP 800-90B] Consider increasing the number of iterations in jent_random_data to support a full entropy claim

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#34]
The ambient assumption in the library seems to be that the lower bound for the per-delta min entropy is `1/osr`, and it appears the intent is to have full-entropy output from the entropy source.

To make a full entropy claim for a m-bit output from a vetted conditioning function, the current draft SP 800-90C requires inputting m+64 bits of min entropy. In this code base, I think that would be accomplished by changing ``jent_random_data``  so that the second if statement reads:

```
#define ENTROPY_SAFETY_FACTOR 64
                if (++k >= ((DATA_SIZE_BITS+ENTROPY_SAFETY_FACTOR) * ec->osr))
                        break;
```

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 22.04.2021 um 10:29 -0700 schrieb Joshua E. Hill:
> The ambient assumption in the library seems to be that the lower bound for
> the per-delta min entropy is `1/osr`, and it appears the ultimate desire is
> to have full-entropy output from the entropy source.
> 
> To make a full entropy claim for a m-bit output from a vetted conditioning
> function, the current draft SP 800-90C requires inputting m+64 bits of min
> entropy. In this code base, I think that would be accomplished by changing
> ``jent_random_data``  so that the second if statement reads:
> 
> ```
> #define ENTROPYSAFETYFACTOR 64
>                 if (++k >= ((DATA_SIZE_BITS+ENTROPYSAFETYFACTOR) * ec->osr))
>                         break;
> ```
> 

Sure, that can be done. But I am a bit at a loss to why m+64 is considered by
90C. basically, the loop generates 256 * osr time deltas. The 90B tool set and
all other assessments show that this approach delivers at least 256 bits of
entropy for one output block of 256 bits - i.e. block is believed to have full
entropy.

When adding 64 more time deltas, we add more entropy to the buffer which
cannot hold more entropy. Effectively we increase the OSR by 64/256 * OSR =
192/256.

Again, I am not against such approach. I would just like to understand (1) why
such an approach is suggested by 90C and (2) why it is 64, and not a
percentage of the block size (e.g. if you have another noise source with a
block size of, say, 64, the 90C requirement seems to be more harsh than for
the Jitter RNG).

Thanks a lot
Stephan

**Comment by joshuaehill** [comment]
In that chunk of code, you are using `jent_measure_jitter` to accumulate random data into ec->data. There isn't a buffering issue that I can think of here, because it all gets hashed into the same 256 bits.

The output 256 bits can receive more than 256 bits of min entropy, of course, but the 256-bit output of SHA3-256(M) can only asymptotically approach 256 bits of min entropy, not attain that bound. Random maps will tend to have collisions, which reduces the creditable output entropy (that is what SP 800-90B Section 3.1.5.1.2 attempts to bound).

The value "64" is justified in Appendix A of the current 90C draft, and aligns with NIST's in "epsilon" definition in this document, which is that a string can be considered "full entropy" if you can bound the min entropy in each bit of output to at least 1-epsilson, where epsilon is  required to be <= 2^(-32).

**Comment by joshuaehill** [comment]
[After re-reading your reply, I realized that I had misunderstood one of your statements, so my previous first paragraph was a response to a statement that you didn't make. My apologies for any confusion. An edited version follows.]

The output 256 bits can receive more than 256 bits of min entropy, of course, but the 256-bit output of SHA3-256(M) can only asymptotically approach 256 bits of min entropy, not attain that bound. Random maps will tend to have output collisions, which reduces the creditable output entropy (that is what SP 800-90B Section 3.1.5.1.2 attempts to bound).

The value "64" is justified in Appendix A.4 of the current 90C draft, and aligns with NIST's in "epsilon" definition in this document, which is that a string can be considered "full entropy" if you can bound the min entropy in each bit of output to at least 1-epsilson, where epsilon is  required to be <= 2^(-32).

**Comment by smuellerDD** [comment]
Thank you for you detailed explanation.

Patch applied.
