### ISSUE TITLE
[SP 800-90B] The built-in APT and RCT cutoffs do not correspond to the stated false positive rate

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#45]
The stated desired false positive rate is 2^(-30).

For a presumed entropy lower bound of `H=1/osr`, this translates to `C=1+30*osr` for the RCT test . The counting in this library starts at 0 rather than 1, so the corresponding cutoff for this library is `30*osr`, rather than `31*osr`.

Similarly, for `osr=1`, the cutoff for the APT is indeed `C=325`, but again this library starts counting at 0 rather than 1, so the corresponding cutoff for this library should be `324`. If we wanted the APT cutoff to scale as the RCT does, then these cutoff for other `osr` values either should be calculated real time, or alternately hardcoded into a table.

Some additional notes: The APT cutoff formula in 90B has a small problem, so actually this formula should be slightly corrected; this is detailed the [SP 800-90B comment 10b here](https://www.untruth.org/~josh/sp80090b/UL%20SP800-90B-final%20comments%20v1.9%2020191212.pdf). This does not impact most of these values (though there is a difference of 1 for `osr=3` and `osr=5`)

Also, note that the desired cutoff of the implemented APT test is different than described above (due to issue #46), but I don't see much point in calculating the correct cutoff value for the current (erroneous) implementation.

**Comment by smuellerDD** [comment]
Am Sonntag, 13. Juni 2021, 19:41:35 CEST schrieb Joshua E. Hill:

Hi Joshua,

> The stated desired false positive rate is 2^(-30).
> 
> For a presumed entropy lower bound of `H=1/osr`, this translates to
> `C=1+30*osr` for the RCT test and `C=325` for the APT. The counting in this
> library starts at 0 rather than 1, so the corresponding cutoff for this
> library is `30*osr`, rather than `31*osr`.

Correct, fixed for RCT by replacing >= with >

> 
> Similarly, for `osr=1`, the cutoff for the APT is indeed `C=325`, but again
> this library starts counting at 0 rather than 1, so the corresponding
> cutoff for this library should be `324`.

Changed  >= to > 

This should do the trick.

> If we wanted the APT cutoff to
> scale as the RCT does, then these cutoff for other `osr` values either
> should be calculated real time, or alternately hardcoded into a table.

If I see that correctly, it should be similar to RCT:

if (ec->apt_count > JENT_APT_CUTOFF * ec->osr)

> 
> Some additional notes: The APT cutoff formula in 90B has a small problem, so
> actually this formula should be slightly corrected; this is detailed the
> [SP 800-90B comment 10b
> here](https://www.untruth.org/~josh/sp80090b/UL%20SP800-90B-final%20comment
> s%20v1.9%2020191212.pdf). This does not impact most of these values (though
> there is a difference of 1 for `osr=3` and `osr=5`)

Do you see an issue when we leave the APT at 325 as is? As we use alpha=-30, 
the off-by-one would translate to a slightly smaller alpha which is still well 
within the range of -20 to -40.

Ciao
Stephan

**Comment by joshuaehill** [comment]
> If I see that correctly, it should be similar to RCT: `if (ec->apt_count > JENT_APT_CUTOFF * ec->osr)`

No, I don't think that it scales like this (you need to use the binomial theorem, which doesn't scale in this way). For the correct cutoffs, see the `jent_apt_cutoff_lookup` in PR #40.

**Comment by smuellerDD** [comment]
Am Sonntag, 13. Juni 2021, 22:28:31 CEST schrieb Joshua E. Hill:

Hi Joshua,

> > If I see that correctly, it should be similar to RCT: `if (ec->apt_count >
> > JENT_APT_CUTOFF * ec->osr)`
> No, I don't think that it scales like this (you need to use the binomial
> theorem, which doesn't scale in this way). For the correct cutoffs, see the
> `jent_apt_cutoff_lookup` in PR #40.

Ok, I will leave the item open, but push a commit with the mentioned changes, 
thanks.

Ciao
Stephan

**Comment by joshuaehill** [comment]
> Correct, fixed for RCT by replacing >= with >

I may misunderstand, but it sounds like you are proposing changing the code to look like this:
```
if ((unsigned int)ec->rct_count > (31 * ec->osr)) {
	ec->rct_count = -1;
	ec->health_failure = 1;
}
```

This change would make things worse. In 90B terms for your stated false positive rate of 2^(-30) and for `osr=1`, your existing cutoff is `C=32`, whereas it should be `C=31`. If you changed the comparison as I think that you described, then the cutoff would instead be `C=33`. For `osr=2`, the desired cutoff is (again, in 90B terms) `C=61`, but with your proposed change you effectively have the cutoff `C=64`.

> Do you see an issue when we leave the APT at 325 as is? As we use alpha=-30, the off-by-one would translate to a slightly smaller alpha which is still well within the range of -20 to -40.

For an implementation of the approved APT and RCT, almost any choice of alpha is compliant (the alpha range that you highlight is a recommended range, not a required range). That said, neither this APT nor RCT are implementations of the approved health tests (for explanation, see issue #46 for the current APT, and Issue #23 for the RCT), and this results in having to argue compliance to the Section 4.5 requirements. These additional requirements on developer-defined health tests impose statistical power requirements for certain failure modes, which in turn induces a specific (test-specific) upper bound for alpha.

I don't expect that these issues render the health tests as non-90B compliant under common settings for `osr`; the main 90B **compliance** issue here is that the documentation in the code and the separate documentation package are both incorrect and misleading, and the code implementing the APT and RCT is somewhat opaque (which is presumably what led to these bugs in the first place).

**Comment by smuellerDD** [comment]
I hope all your concerns are fixed with the merge of your patches. I am closing this one. Please feel free to reopen if I left something open.
