### ISSUE TITLE
[SP 800-90B] The implemented APT test is not quite the SP 800-90B APT test

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#46]
The flow of the implemented APT test is roughly:

- The APT state is implicitly initialized when the `rand_data` structure is zeroed on allocation.
- The first symbol input causes `apt_base_set` to be set, and sets `apt_count` or `apt_observations` to 0.
- Once the `apt_base_set` is set, further insertions increment `apt_count` if the new symbol equals the `apt_base` symbol and `apt_observations` is incremented each time. AFTER `apt_observations` is incremented, the total number of symbols examined within the window is  `apt_observations+1` (counting the initial symbol, as directed in 90B). Once `apt_observations` is greater than or equal to 512, the apt is reset, and the current symbol is made the new reference symbol.

I think that there are two issues here: 
1. The base symbol isn't ever counted toward the window size. This isn't what 90B directs, and the resulting window size is actually (in 90B terms) 513, rather than the desired 512.
2. For windows other than the first, the last value seen **in the prior window** establishes the base value in the current window. The 90B APT test consistently uses the first value of the window as the reference value, not the last value from the prior window.

From a technical perspective, I don't think that really has much of an effect, as the test still basically works the same way. From a compliance perspective, this isn't the APT test described in 90B, and so this has to instead be dealt with as a developer-defined health test.

**Comment by smuellerDD** [comment]
I hope all your concerns are fixed with the merge of your patches. I am closing this one. Please feel free to reopen if I left something open.
