### ISSUE TITLE
[SP 800-90B] Repeated deterministic output patterns as an anticipated failure mode

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#47]
SP 800-90B Section 4.3 Requirement #8 states:

> “The submitter shall provide documentation of any known or suspected noise source failure modes (e.g., the noise source starts producing periodic outputs like 101…01), and shall include developer-defined continuous tests to detect those failures. These should include potential failure modes that might be caused by an attack on the device.”

In the [document describing this library](http://www.chronox.de/jent/doc/CPU-Jitter-NPTRNG.pdf), Section 7.2.41, it states that there are no known or suspected noise source failure modes. This may be misleading on some architectures, as the `jent_entropy_init` function includes start-up health tests for a number of conditions:

1. The timer value is ever 0 (resulting in a `ENOTIME` return code).
2. The delta value is ever 0 (resulting in a `ECOARSETIME` return code).
3. The delta value is stuck (that is, the timer value, delta or second delta are fixed between two consecutive delta values) more than 90% of the time (resulting in a `ESTUCK` return code).
4. The timer runs backwards more than 3 times over the `JENT_POWERUP_TESTLOOPCOUNT` iterations (resulting in a `ENOMONOTONIC` return code).
5. The delta value is divisible by 100 more than 90% of the time (resulting in a `ECOARSETIME` return code). This test is generalized in PR #43.
6. Consecutive delta values are, on average, less than 1 apart from each other (resulting in a `EMINVARVAR` return code). 

On some architectures these failure modes may be profoundly unlikely to occur, and thus one could say that on such architectures these are not anticipated failure modes for that fixed hardware, though these tests continue to exist in any case.

During testing, another important failure mode was encountered several times, and should probably be considered “anticipated”: in certain circumstances (particularly when the optimizer has not been disabled), repeated deterministic patterns of various lengths can emerge. The apparent variation in such deterministic patterns does not contribute entropy, so large numbers of such strings should be detected and an error should be raised.

**Comment by smuellerDD** [comment]
Thanks for the report. Considering the work on the lag predictor test, I would assume that an approach is now discussed that should cover this concern.

Allow me to close it. If you think it should not be closed, please reopen.
