### ISSUE TITLE
[SP 800-90B] Start-up health tests performed on data that isn't produced by the noise source used everywhere else

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#48]
This library uses an approximation for the raw source in `jent_time_entropy_init`, so it is not clear if the testing performed in this function can be treated as start-up health testing.

Further, because `ec.mem` is not initialized within `jent_time_entropy_init`, `jent_memaccess` never  produced significant variation within the noise source while conducting the start-up health tests. This is a problem for two reasons:

1. The lack of variation produced by `jent_memaccess` would lead to more start-up failures than should occur.
2. As `jent_memaccess` is normally used in the noise source, this makes the functionality tested in `jent_time_entropy_init` distinct from the normal noise source, so it's not clear that the functionality in `jent_time_entropy_init` can be treated as a start-up health test for the purposes of SP 800-90B.

If the data tested within `jent_time_entropy_init` is not deemed start-up health testing, then the JEnt Entropy Source is not compliant with the health testing requirements of SP 800-90B (in particular, Section 4.3 Requirement 4).

**Comment by smuellerDD** [comment]
I hope all your concerns are fixed with the merge of your patches. I am closing this one. Please feel free to reopen if I left something open.
