### ISSUE TITLE
1-core rng-tools jitterentropy always fails

### ISSUE THREAD

**Issue by abelbeck** [smuellerDD/jitterentropy-library#5]
Hi @smuellerDD , I have done some testing with our AstLinux project, cross-compiled to i586 and x86_64 targets.  We are using your latest jitterentropy 9048af7f statically linked in rng-tools 6.4.

Given a few cross-compile fixes, shared with Neil, all is good.

One issue is 1-core (bare metal and VM's) jitterentropy always exits.  For example ...

1) Testing on a Soekris 1-core net5501, 1-core vultr (hosted KVM/QEMU) and 1-core VMware Fusion VM, rngd always exits.
```
pbx ~ # rngd -f -d -x0 -x1 -x2
Disabling 0: Hardware RNG Device

Disabling 1: TPM RNG Device

Disabling 2: Intel RDRAND Instruction RNG


Initalizing available sources

Limiting thread count to 1 active cpus

JITTER starts 1 threads

Enabling JITTER rng support

JITTER skips thread on cpu 0

Reading entropy from JITTER Entropy generator

...previous 2 lines repeating 10's of times...

No entropy sources working, exiting rngd

JITTER thread on cpu 0 wakes up for refill
(rngd exits)
```
2) Testing on a 2-core VMware Fusion VM, rngd keeps running, but /proc/sys/kernel/random/entropy_avail stays around 200.

3) Testing on a 4-core VMware Fusion VM, rngd keeps running, and /proc/sys/kernel/random/entropy_avail quickly goes over 3000.

4) Both my Lanner LEC-7220-N4 and PC Engines APU2 default to jitterentropy, each with 4-cores, and works nicely with /proc/sys/kernel/random/entropy_avail over 3000.

Does the laws of physics say 1-core will not converge, should 1-core devices try to use multiple jitterentropy threads ?

Any insight is appreciated.

**Comment by abelbeck** [comment]
@nhorman Is the issue described above fixed by your recent 8fbbed0b commit ?

**Comment by abelbeck** [comment]
@nhorman , Brilliant !  your recent 8fbbed0b commit  fixed it !

1-core VM's Vultr and VMware (haven't tried net5501 yet) work perfectly with the default `-O 5:retry_count:1` setting.  /proc/sys/kernel/random/entropy_avail quickly goes over 3000.

If I use `-O 5:retry_count:0` I get the same problem as described above, as expected.

@smuellerDD Sorry for the noise here. :-)

**Comment by smuellerDD** [comment]
Am Samstag, 1. September 2018, 01:08:33 CEST schrieb Lonnie Abelbeck:

Hi Lonnie,
> 
> @smuellerDD Sorry for the noise here. :-)

Just to clarify: All is working as expected and there is nothing left open for 
me?

Ciao
Stephan

**Comment by nhorman** [comment]
I concur with @smuellerDD .  Usually the quick and dirty test I use is to start rngd with the entropy source I wish to measure, while in a second terminal I run a test program that reads from /dev/random, while recording the time for each read access, using that information to compute the number of random bytes per second I can pull.

**Comment by abelbeck** [comment]
@smuellerDD @nhorman Your insights are much appreciated.

How about the quality of the randomness, is looking for the lower `FIPS 140-2 failures:` with the `/dev/urandom` tests I performed above give some correlation to the RNG's randomness, or is this too complex of an topic to boil down on a command-line test in a Github comment ?

**Comment by nhorman** [comment]
The rngtest utility provides the fips 140-2 pattern test iirc.  Anything
regarding random quality after that requires some significant additional
computation that I don't have a test for.  Do you @smullerDD?
Neil

**Comment by smuellerDD** [comment]
Am Montag, 3. September 2018, 15:36:30 CEST schrieb Neil Horman:

Hi Neil,

> The rngtest utility provides the fips 140-2 pattern test iirc.

I am not sure where the reference to FIPS 140-2 comes from (I always wondered 
when I looked into the rngd sources). The 5 tests are all from BSI AIS20/31. I 
have not seen them being referenced as part of FIPS 140(-2).

> Anything
> regarding random quality after that requires some significant additional
> computation that I don't have a test for.  Do you @smullerDD?

Sure: dieharder, ent, SP800-90B tests :-)

But note, it is the nature of random processes that a particular random number 
may *not* be in the middle of some expected distributions.

For example, ent delivers the results for the commonly quite good Chi-Squared 
test. Yet, even if you have an SP800-90A DRBG (which produces white noise), it 
may happen occasionally that a random number falls outside of a given 
confidence interval of the Chi-Squared test.

If you think about it: there must be occasions where it falls outside as 
otherwise not the entire continuum of possible values are utilized. For 
example, it may happen that a random number is 0x00000, or 0xfffff, but that 
must occur with a probability defined by the equidistribution.

That said it is utmost important to interpret any results from these tools and 
not take the face value to decide whether a noise source has a defect.


Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, 3. September 2018, 15:33:25 CEST schrieb Lonnie Abelbeck:

Hi Lonnie,

> @smuellerDD @nhorman Your insights are much appreciated.
> 
> How about the quality of the randomness, is looking for the lower `FIPS
> 140-2 failures:` with the `/dev/urandom` tests I performed above give some
> correlation to the RNG's randomness, or is this too complex of an topic to
> boil down on a command-line test in a Github comment ?

I am not sure that brings anything. Only if you happen to have a good 
understanding of your noise source, you can apply a test (and then only to the 
raw, unconditioned noise data). Applying an arbitrary test to an unknown noise 
source is meaningless. This is especially the case if the noise was post-
processed with cryptographic primitives as in this case you only test the 
quality of these primitives.

For example, if you apply the rngd test to RDRAND you may find very occasional 
statistical weaknesses reported by the measurement tools. But this (as said in 
the other mail) is kind of expected. RDRAND implements a CTR DRBG with AES256 
core, no derivation function and no prediction resistance. Thus, it is a good 
and recognized deterministic random number generation which will always 
generated white noise. Any statistical test of the output is meaningless. That 
said, you would need to test the raw noise (which you cannot get to from the 
rngd perspective).

Same with the Jitter RNG: The output is the result of an LFSR with a primitive 
and irreducible polynomial which also produces white noise. Any statistical 
test is meaningless. Again you would need to test the raw noise which you 
cannot get to.

Thus, all that we can do for rngd is to assess the used noise sources to see 
whether they implement statistical tests for their raw noise to identify noise 
source failures. For my Jitter RNG for example, the test is implemented in 
jent_stuck.

Ciao
Stephan

**Comment by abelbeck** [comment]
@smuellerDD Thanks for the detailed insights.
