### ISSUE TITLE
In `jent_read_entropy_safe` osr is not actually incremented

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#54]
In `jent_read_entropy_safe`, the code `jent_entropy_collector_alloc(osr++, flags)` **post-increments** the `osr` value (that is, the value passed into the function is osr, not osr+1).  As a consequence,  this function never causes the `osr` value in the collector context to increase.

This can be seen by running the following program:
```
#include <stdio.h>
int main(void) {
        int x = 0;
        printf("x in call: %d\n", x++);
        printf("x after call: %d\n", x);
        return 0;
}
```

This results in the following output:
```
x in call: 0
x after call: 1
```

This should be fixed by either using a pre-increment (`++osr`) or (perhaps more clearly) just explicitly adding adding one when that variable is initilized (`osr = (*ec)->osr + 1`) or when it is called `jent_entropy_collector_alloc(osr+1, flags)`.

**Comment by smuellerDD** [comment]
Palmface.

Thanks for spotting this. It is now fixed.
