### ISSUE TITLE
Failure to compile due to OS CFLAGS containing optimisation setting

### ISSUE THREAD

**Issue by dermotbradley** [smuellerDD/jitterentropy-library#55]
Hi

I'm the Alpine Linux package maintainer for jitterentropy-library.

In preparation for the soon-to-be-related 3.1.0 I updated my Alpine packaging to test the Git "master".

The compile is failing with file src/jitterentropy-base.c:

src/jitterentropy-base.c:58:3: error: #error "The CPU Jitter random number generator must not be compiled with optimizations. See documentation. Use the compiler switch -O0 for compiling jitterentropy.c."
   58 |  #error "The CPU Jitter random number generator must not be compiled with optimizations. See documentation. Use the compiler switch -O0 for compiling jitterentropy.c."

I noticed that "gcc" was being called with both "-Os" (actually it appears twice in the gcc command, both at the start and at the end) and "-O0":

```
gcc -Os -fomit-frame-pointer -Wextra -Wall -pedantic -fPIC -O0 -fwrapv -Wconversion -fstack-protector-strong -I. -Isrc -Os -fomit-frame-pointer  -c -o src/jitterentropy-timer.o src/jitterentropy-timer.c
src/jitterentropy-base.c:58:3: error: #error "The CPU Jitter random number generator must not be compiled with optimizations. See documentation. Use the compiler switch -O0 for compiling jitterentropy.c."
   58 |  #error "The CPU Jitter random number generator must not be compiled with optimizations. See documentation. Use the compiler switch -O0 for compiling jitterentropy.c."

```

Looking at the Makefile I changed line 5 from "CFLAGS +=" to "CFLAGS =" so that the Makefile replaced rather than appended to the existing CFLAG settings which resulting in this output:

```
gcc -Wextra -Wall -pedantic -fPIC -O0 -fwrapv -Wconversion -fstack-protector-strong -I. -Isrc -Os -fomit-frame-pointer  -c -o src/jitterentropy-timer.o src/jitterentropy-timer.c
src/jitterentropy-base.c:58:3: error: #error "The CPU Jitter random number generator must not be compiled with optimizations. See documentation. Use the compiler switch -O0 for compiling jitterentropy.c."
   58 |  #error "The CPU Jitter random number generator must not be compiled with optimizations. See documentation. Use the compiler switch -O0 for compiling jitterentropy.c."
```

Whilst this change prevented "-Os" appearing at the start of the gcc command options it still however appeared towards the end. I'm confused how this is happening.

So I'm struggling how to ensure that Alpine (abuild) "-Os" setting does not leak into the Makefile. Potentially the same issue could occur with any distribution and so the jitterentropy-library Makefile should manage this somehow.

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 14.07.2021 um 12:00 -0700 schrieb dermotbradley:
> Hi

Hi,
> 
> I'm the Alpine Linux package maintainer for jitterentropy-library.
> 
Please to meet you.

> In preparation for the soon-to-be-related 3.1.0 I updated my Alpine
> packaging to test the Git "master".
> 
> The compile is failing with file src/jitterentropy-base.c:
> 
> src/jitterentropy-base.c:58:3: error: #error "The CPU Jitter random number
> generator must not be compiled with optimizations. See documentation. Use
> the compiler switch -O0 for compiling jitterentropy.c."
>    58 |  #error "The CPU Jitter random number generator must not be compiled
> with optimizations. See documentation. Use the compiler switch -O0 for
> compiling jitterentropy.c."
> 
> I noticed that "gcc" was being called with both "-Os" (actually it appears
> twice in the gcc command, both at the start and at the end) and "-O0":
> 
> ```
> gcc -Os -fomit-frame-pointer -Wextra -Wall -pedantic -fPIC -O0 -fwrapv -
> Wconversion -fstack-protector-strong -I. -Isrc -Os -fomit-frame-pointer  -c
> -o src/jitterentropy-timer.o src/jitterentropy-timer.c
> src/jitterentropy-base.c:58:3: error: #error "The CPU Jitter random number
> generator must not be compiled with optimizations. See documentation. Use
> the compiler switch -O0 for compiling jitterentropy.c."
>    58 |  #error "The CPU Jitter random number generator must not be compiled
> with optimizations. See documentation. Use the compiler switch -O0 for
> compiling jitterentropy.c."
> 
> ```
> 
> Looking at the Makefile I changed line 5 from "CFLAGS +=" to "CFLAGS =" so

Try := instead of an = 

For Makefiles, the complete full assignment is with a colon-equal sign.

Ciao
Stephan


> that the Makefile replaced rather than appended to the existing CFLAG
> settings which resulting in this output:
> 
> ```
> gcc -Wextra -Wall -pedantic -fPIC -O0 -fwrapv -Wconversion -fstack-
> protector-strong -I. -Isrc -Os -fomit-frame-pointer  -c -o
> src/jitterentropy-timer.o src/jitterentropy-timer.c
> src/jitterentropy-base.c:58:3: error: #error "The CPU Jitter random number
> generator must not be compiled with optimizations. See documentation. Use
> the compiler switch -O0 for compiling jitterentropy.c."
>    58 |  #error "The CPU Jitter random number generator must not be compiled
> with optimizations. See documentation. Use the compiler switch -O0 for
> compiling jitterentropy.c."
> ```
> 
> Whilst this change prevented "-Os" appearing at the start of the gcc command
> options it still however appeared towards the end. I'm confused how this is
> happening.
> 
> So I'm struggling how to ensure that Alpine (abuild) "-Os" setting does not
> leak into the Makefile. Potentially the same issue could occur with any
> distribution and so the jitterentropy-library Makefile should manage this
> somehow.

> 
>

**Comment by dermotbradley** [comment]
> Try := instead of an =
>
> For Makefiles, the complete full assignment is with a colon-equal sign.

That had the same effect as "=", it removed the "-Os -fomit-frame-pointer" value from the start of the gcc calls.

However "-Os -fomit-frame-pointer" still appears at the end of the gcc call. Somehow the existing CFLAGS value is being appended (as well as prepend before the above change).

**Comment by dermotbradley** [comment]
It is compiled now with the following patch:

```
diff -aur a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,8 @@
 CC ?= gcc
 #Hardening
 CFLAGS ?= -fwrapv --param ssp-buffer-size=4 -fvisibility=hidden -fPIE -Wcast-align -Wmissing-field-initializers -Wshadow -Wswitch-enum
-CFLAGS +=-Wextra -Wall -pedantic -fPIC -O0 -fwrapv -Wconversion
+CFLAGS :=-Wextra -Wall -pedantic -fPIC -O0 -fwrapv -Wconversion
+CPPFLAGS := $(CFLAGS)
 LDFLAGS +=-Wl,-z,relro,-z,now -lpthread
 
 GCCVERSIONFORMAT := $(shell echo `$(CC) -dumpversion | sed 's/\./\n/g' | wc -l`)
```

**Comment by smuellerDD** [comment]
Am Mittwoch, 14. Juli 2021, 22:15:06 CEST schrieb dermotbradley:

Hi dermotbradley,

> It is compiled now with the following patch:
> 
> ```
> diff -aur a/Makefile b/Makefile
> --- a/Makefile
> +++ b/Makefile
> @@ -3,7 +3,8 @@
>  CC ?= gcc
>  #Hardening
>  CFLAGS ?= -fwrapv --param ssp-buffer-size=4 -fvisibility=hidden -fPIE
> -Wcast-align -Wmissing-field-initializers -Wshadow -Wswitch-enum -CFLAGS
> +=-Wextra -Wall -pedantic -fPIC -O0 -fwrapv -Wconversion
> +CFLAGS :=-Wextra -Wall -pedantic -fPIC -O0 -fwrapv -Wconversion
> +CPPFLAGS := $(CFLAGS)
>  LDFLAGS +=-Wl,-z,relro,-z,now -lpthread
> 
>  GCCVERSIONFORMAT := $(shell echo `$(CC) -dumpversion | sed 's/\./\n/g' | wc
> -l`) ```

Oh, I see, CPPFLAGS are also set

You should be able to set:

CFLAGS := <normal flags>
CPPFLAGS :=

I.e. you reassign CPPFLAGS to an empty string.

Ciao
Stephan

**Comment by dermotbradley** [comment]
True, setting it to an empty value makes more sense.

Danke dir
