### ISSUE TITLE
Does not compile for windows

### ISSUE THREAD

**Issue by ronaaron** [smuellerDD/jitterentropy-library#56]
Previous versions did compile using mingw64 (TDM version).

Now, the base-user.h file line 216 fails because of the sysconf() call.

**Comment by smuellerDD** [comment]
I pushed a change, please test.

**Comment by ronaaron** [comment]
Sorry, same issue, because 'mingw' compilers are gnuc...

```
rc/jitterentropy-base-user.h: In function 'long int jent_ncpu()':
src/jitterentropy-base-user.h:217:22: error: '_SC_NPROCESSORS_ONLN' was not declared in this scope
  long ncpu = sysconf(_SC_NPROCESSORS_ONLN);
                      ^
src/jitterentropy-base-user.h:217:42: error: 'sysconf' was not declared in this scope
  long ncpu = sysconf(_SC_NPROCESSORS_ONLN);
```

A better test would be `#ifndef WIN32`

**Comment by smuellerDD** [comment]
Am Freitag, dem 16.07.2021 um 00:20 -0700 schrieb ronaaron:
> Sorry, same issue, because 'mingw' compilers are gnuc...
> 
> ```
> rc/jitterentropy-base-user.h: In function 'long int jent_ncpu()':
> src/jitterentropy-base-user.h:217:22: error: '_SC_NPROCESSORS_ONLN' was not
> declared in this scope
>   long ncpu = sysconf(_SC_NPROCESSORS_ONLN);
>                       ^
> src/jitterentropy-base-user.h:217:42: error: 'sysconf' was not declared in
> this scope
>   long ncpu = sysconf(_SC_NPROCESSORS_ONLN);
> ```
> 
> A better test would be `#ifndef WIN32`

This is also not going to catch all - sysconf() is a POSIX flag.

Thus, can you please use `#ifdef _POSIX_SOURCE` and let me know?

Thanks
Stephan
>

**Comment by ronaaron** [comment]
Yes, that works.

**Comment by smuellerDD** [comment]
Am Freitag, dem 16.07.2021 um 01:06 -0700 schrieb ronaaron:
> Yes, that works.
> 

Patch pushed.
