### ISSUE TITLE
GCD: analysis code misses first time delta?

### ISSUE THREAD

**Issue by smuellerDD** [smuellerDD/jitterentropy-library#59]
jent_gcd_analyze seems to miss the analysis of delta_history[0] for the GCD calculation. Thus, shouldn't the following line be added before the for loop?

```
running_gcd = jent_gcd64(delta_history[0], running_gcd);
```

**Comment by joshuaehill** [comment]
That's a good catch, but the first value is necessarily the result of the gcd calculation, so you could simply use
```
if(nelem > 0) {
  running_gcd=delta_history[0];
} else {
  return 0;
}
```
prior to the first loop in `jent_gcd_analyze`.

**Comment by smuellerDD** [comment]
Thank you - patch applied.
