### ISSUE TITLE
request to tag a new release

### ISSUE THREAD

**Issue by nhorman** [smuellerDD/jitterentropy-library#6]
Hey-
     I'd like to package jitterentropy as a library for fedora, but there are several fixes I need since the v2.1.1 release. Would it be possible to tag a v2.2.2 release with those fixes included so that I don't have to resort to snapshot package naming?

**Comment by smuellerDD** [comment]
Am Donnerstag, 6. September 2018, 17:01:06 CEST schrieb Neil Horman:

Hi Neil,

> Hey-
>      I'd like to package jitterentropy as a library for fedora, but there
> are several fixes I need since the v2.1.1 release. Would it be possible to
> tag a v2.2.2 release with those fixes included so that I don't have to
> resort to snapshot package naming?

I will release a v2.1.2 tonight.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Done.
