### ISSUE TITLE
jitterentropy-hashtime in 3.0.2

### ISSUE THREAD

**Issue by dtudor-dt** [smuellerDD/jitterentropy-library#61]
Hi Stephan,

Just wanted to confirm something. Starting with 3.0.2, if the flag JENT_CONF_DISABLE_LOOP_SHUFFLE is enabled (and it is by default) the raw output generated by the jitterentropy-hashtime test is no longer separated in a regular case and a lower bound case. In both cases, the OSR is set to the minimum value, 3, and the loop count is set to 1. Is that correct?

If that's true, should the lower bound case force an OSR of 1 to replicate the pre-3.0.2 behavior?

Thank you,
Dragos

**Comment by joshuaehill** [comment]
The `jitterentropy-hashtime` function is outputs raw data (i.e., prior to hashing), so the setting of `osr` (which establishes how many raw samples are fed into the hash per hash output) doesn't directly affect the data being output from `jitterentropy-hashtime`.

When `JENT_CONF_DISABLE_LOOP_SHUFFLE` is defined, the first and second column of outputs from the `jitterentropy-hashtime` have basically the same behavior (other than the second column is sampled later).

Which pre-3.0.2 behavior are you trying to replicate?

**Comment by dtudor-dt** [comment]
I just noticed other issues that were discussing this change, so my mistake. 

So, the pre-3.0.2 behavior was that one column had raw data that was imitating the real behavior of the rngd process (the var case) and one column that had only the lower bound (the single case). Now that difference is removed, right? The rngd behavior is the minimum, lower bound case.

**Comment by joshuaehill** [comment]
By default, the pseudorandom variation produced by the `jent_loop_shuffle` function is no longer used in any mode (either testing, or while operating normally). As a consequence, the first and second columns produced by `jitterentropy-hashtime` should mostly show the same behavior.

The pseudorandom variation induced by `jent_loop_shuffle` can be turned back on by removing the `JENT_CONF_DISABLE_LOOP_SHUFFLE` macro prior to compiling the library.

**Comment by dtudor-dt** [comment]
That cleared things up, thanks a lot.

Would you recommend keeping the  `JENT_CONF_DISABLE_LOOP_SHUFFLE` macro is the end goal is to pass an SP800-90B validation?

**Comment by joshuaehill** [comment]
Yes. [Here ](https://www.untruth.org/~josh/sp80090b/What%20To%20Expect%20When%20You're%20Expecting%20(to%20Evaluate%20JEnt%20Against%20SP%20800-90B)%2020210727-3.pdf)is a presentation that I gave on this topic.

**Comment by dtudor-dt** [comment]
Great, thank you.
