### ISSUE TITLE
Allow using alternate 'malloc/free'

### ISSUE THREAD

**Issue by ronaaron** [smuellerDD/jitterentropy-library#65]
I am using an alternative memory allocator, and on Windows I can't reliably override malloc/free.

Can you please use `#ifdef JITTER_MALLOC`, etc to permit use of an alternate malloc/free?

**Comment by smuellerDD** [comment]
Am Sonntag, 15. August 2021, 09:03:28 CEST schrieb ronaaron:

Hi ronaaron,

> I am using an alternative memory allocator, and on Windows I can't reliably
> override malloc/free.
> 
> Can you please use `#ifdef JITTER_MALLOC`, etc to permit use of an alternate
> malloc/free?

The purpose of jitterentropy-base-user.h is to have the functions in there 
replaced by you, if you have a need for that. Those functions are the ones 
that may not be portable. All other functions used in Jitter RNG rest on C 
(except memset amd memcpy which I expect to be present everywhere.

Thus, modify the header file as needed.

Ciao
Stephan
