### ISSUE TITLE
i have a question about pdf7.2.6 (Non-vetted Conditioning Components)

### ISSUE THREAD

**Issue by yuyinw** [smuellerDD/jitterentropy-library#68]
Hello 
       I see the pdf7.2.6  Components calculation process 。
       uses these parameters  :    hin=64  hin=4096   nw=64  nout=64,  

       But when i use SP800-90B_EntropyAssessment tools, it print result nan:
                  yy@localhost cpp]$ ./ea_conditioning -v -n 4096 64  64 64 1
                  n_in: 4096.000000
                  n_out: 64.000000
                  nw: 64.000000
                  h_in: 64.000000
                  h': 1.000000
                  
                  (Non-vetted) h_out: nan

**Comment by smuellerDD** [comment]
Am Montag, dem 06.09.2021 um 01:26 -0700 schrieb yuyinw:
> Hello 
>        I see the pdf7.2.6  Components calculation process 。
>        uses these parameters  :    hin=64  hin=4096   nw=64  nout=64,  
> 
>        But when i use SP800-90B_EntropyAssessment tools, it print result
> nan:
>                   ***@***.*** cpp]$ ./ea_conditioning -v -n 4096 64  64 64
> 1
>                   n_in: 4096.000000
>                   n_out: 64.000000
>                   nw: 64.000000
>                   h_in: 64.000000
>                   h': 1.000000
>                   
>                   (Non-vetted) h_out: nan

I would infer from you invocation you process 2.2.0? If so, why do you use -v?
Shouldn't it be -n considering it is an LFSR?

Ciao
Stephan

**Comment by yuyinw** [comment]
Hi smuellerDD
    Sorry,  LFSR is Non-vetted Conditioning Components and should not user -v. But the result is same 
    [wy@localhost cpp]$ ./ea_conditioning  -n 4096 64  64 64 1
    n_in: 4096.000000
    n_out: 64.000000
    nw: 64.000000
    h_in: 64.000000
    h': 1.000000
    
    (Non-vetted) h_out: nan

**Comment by joshuaehill** [comment]
It's a precision problem with the NIST tool. This is best discussed over on the NIST githib (where you aalready have an issue on the topic).

**Comment by yuyinw** [comment]
Ok.
Thank you  smuellerDD.
Thank you  joshuaehill.
