### ISSUE TITLE
rngd eats a lot of RAM when libjitterentropy is at c185bcf2f87606b60303dc40f8fdd444f105c4b6

### ISSUE THREAD

**Issue by kanavin** [smuellerDD/jitterentropy-library#69]
Something between 3.1.0 and c185bcf2f87606b60303dc40f8fdd444f105c4b6 made rngd from rng-tools (built with libjitterentropy support) eat unhealthy amounts of RAM. ps aux shows:
```
root       328  7.2 48.4 1283444 985008 ?      Ssl  07:52   1:12 /usr/sbin/rngd -r /dev/hwrng
```
(985008 is RSS). I can do additional debugging if needed.

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 08.09.2021 um 01:57 -0700 schrieb Alexander Kanavin:
> Something between 3.1.0 and c185bcf2f87606b60303dc40f8fdd444f105c4b6 made rngd
> from rng-tools (built with libjitterentropy support) eat unhealthy amounts of
> RAM. ps aux shows:
> ```
> root       328  7.2 48.4 1283444 985008 ?      Ssl  07:52   1:12
> /usr/sbin/rngd -r /dev/hwrng
> ```
> (985008 is RSS). I can do additional debugging if needed.

Thank you very much for the reference. The cause of this is very clear to me
and expected. It is the following line that causes the issue:

https://github.com/smuellerDD/jitterentropy-library/blob/master/src/jitterentropy-base.c#L302

I am currently working on reducing it and have a draft patch available that I
plan to push shortly.

Ciao
Stephan
> 
>

**Comment by smuellerDD** [comment]
Patches applied and released.
