### ISSUE TITLE
Sent the Requested tests

### ISSUE THREAD

**Issue by TNTBOMBOM** [smuellerDD/jitterentropy-library#7]
I have done the tests needed with Whonix and send it to your email.

**Comment by smuellerDD** [comment]
Am Dienstag, 23. April 2019, 21:54:25 CEST schrieb TNT BOM BOM:

Hi,

> I have done the tests needed with Whonix and send it to your email.

Give me another two days for that as I do not have a decent Internet 
connection at the moment.

Ciao
Stephan
