### ISSUE TITLE
Add a failure callback on health failure in FIPS mode

### ISSUE THREAD

**Issue by DanielOjalvo** [smuellerDD/jitterentropy-library#75]
In certain applications, it may be desirable to have an action taken on health failure in FIPS mode. A function to create that callback would be helpful. I have a potential commit that I will be pushing up shortly.

**Comment by smuellerDD** [comment]
Daniel, I somehow did not receive the code. Could you provide it as a merge request. I am also fine if it is inline to this thread. Thanks.

**Comment by DanielOjalvo** [comment]
`From 1bbab4b1c00f5fa9e02d1c2e9510ac0fa86e89f0 Mon Sep 17 00:00:00 2001
From: DanielOjalvo <d.ojalvo@f5.com>
Date: Wed, 27 Oct 2021 11:13:55 -0700
Subject: [PATCH] Add a callback function to be run on health failure in FIPS
 mode 	modified:   jitterentropy.h 	modified:   src/jitterentropy-health.c

---
 jitterentropy.h            |  7 +++++++
 src/jitterentropy-health.c | 12 ++++++++++++
 2 files changed, 19 insertions(+)

diff --git a/jitterentropy.h b/jitterentropy.h
index a8230c9..55b3d62 100644
--- a/jitterentropy.h
+++ b/jitterentropy.h
@@ -378,6 +378,13 @@ int jent_entropy_init(void);
 JENT_PRIVATE_STATIC
 int jent_entropy_init_ex(unsigned int osr, unsigned int flags);
 
+/* Set a callback to run on health failure in FIPS mode.
+ * This function will take an action determined by the caller.
+ */
+typedef void (*jent_fips_failure_cb)(struct rand_data *ec, unsigned int error_code);
+JENT_PRIVATE_STATIC
+void jent_set_fips_failure_callback(jent_fips_failure_cb j);
+
 /* return version number of core library */
 JENT_PRIVATE_STATIC
 unsigned int jent_version(void);
diff --git a/src/jitterentropy-health.c b/src/jitterentropy-health.c
index 710f790..ebf3959 100644
--- a/src/jitterentropy-health.c
+++ b/src/jitterentropy-health.c
@@ -22,6 +22,14 @@
 #include "jitterentropy.h"
 #include "jitterentropy-health.h"
 
+static jent_fips_failure_cb fips_cb = NULL;
+
+JENT_PRIVATE_STATIC
+void jent_set_fips_failure_callback(jent_fips_failure_cb j)
+{
+	fips_cb = j;
+}
+
 /***************************************************************************
  * Lag Predictor Test
  *
@@ -434,5 +442,9 @@ unsigned int jent_health_failure(struct rand_data *ec)
 	if (!ec->fips_enabled)
 		return 0;
 
+	if (fips_cb && ec->health_failure) {
+		fips_cb(ec, ec->health_failure);
+	}
+	
 	return ec->health_failure;
 }
-- 
2.16.2

`

**Comment by DanielOjalvo** [comment]
Hello,
apologies for the delay on this. I added the patch here. Let me know if you have any difficulties with it.
Dan

[0001-Add-a-callback-function-to-be-run-on-health-failure-.txt](https://github.com/smuellerDD/jitterentropy-library/files/7723651/0001-Add-a-callback-function-to-be-run-on-health-failure-.txt)

**Comment by smuellerDD** [comment]
I have applied it with some changes: the call is only allowed before initialization of the Jitter RNG to prevent a race condition.

Please check whether this is acceptable - if not, please reopen this issue.
