### ISSUE TITLE
Question about linking jitterentropy with openssl

### ISSUE THREAD

**Issue by PeterAdamson** [smuellerDD/jitterentropy-library#81]
I have followed the process to link jitterentropy with openssl and successfully built a corresponding rpm with what I believe is a jitterentropy linked openssl rpm.

I would like to know if there is any way to verify that the link is successful aside from the build process working?

**Comment by smuellerDD** [comment]
Am Donnerstag, 13. Januar 2022, 15:58:49 CET schrieb PeterAdamson:

Hi PeterAdamson,

> I have followed the process to link jitterentropy with openssl and
> successfully built a corresponding rpm with what I believe is a
> jitterentropy linked openssl rpm.
> 
> I would like to know if there is any way to verify that the link is
> successful aside from the build process working?

The library is not providing any visible output. However, you could extend the 
openssl's command version information to query jent_version and display it. 
When that API works, you know you have the Jitter RNG library built in.

Aside from that, the initialization logic has functions that return error 
codes. Handle them appropriately when they occur like showing an error message 
or terminating OpenSSL.

Ciao
Stephan

**Comment by PeterAdamson** [comment]
Thanks for the quick reply and the information, much appreciated!
