### ISSUE TITLE
Support using rdtsc on 32-bit systems

### ISSUE THREAD

**Issue by DanielOjalvo** [smuellerDD/jitterentropy-library#83]
On certain azure systems using 32-bit binaries, clock_gettime is returning failures with Error code 2 (ECOARSETIME), which is “Timer too coarse for RNG”. 

We have a proposed change to jitterentropy-base-user.h and will attach shortly.

**Comment by DanielOjalvo** [comment]
We're able to confirm that it is working on the azure systems we tested.

[32-bit-rdtsc-usage.txt](https://github.com/smuellerDD/jitterentropy-library/files/7929147/32-bit-rdtsc-usage.txt)

Credit should go to:
Ginni Dusgotra
Daniel Ojalvo

**Comment by DanielOjalvo** [comment]
If this change is approved, the exact same change can be made to the jitterentropy-rngd library.

https://github.com/smuellerDD/jitterentropy-rngd

**Comment by smuellerDD** [comment]
Patch applied. It will be added to the rngd with the release of 3.4.0
