### ISSUE TITLE
MIPS64 arch: There is high usage of CPU

### ISSUE THREAD

**Issue by sadashivmadiwalar** [smuellerDD/jitterentropy-library#84]
Hi smueller,

There is high usage of CPU when using latest jitterentropy-rngd-1.2.6 over MIPS64 arch.

Is it expected or any possible solution? Below is log for the same.

root     24042  7.8  0.0   3328  2368 ?        Ss   08:19  10:38 jitterentropy-rngd -p /var/run/jitterentropy-rngd.pid

strace shown lot of request for the given pid.

strace64 -s 200 -p 24042
.....
clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440336696}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440425432}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440514256}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440603112}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440691876}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440781104}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440870384}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440962468}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=441052004}) = 0
....

Kernel Version is : 3.10.59
Arch is: Netlogic XLP700/900 Series.

Thanks,
Sadashiv

**Comment by smuellerDD** [comment]
Am Dienstag, 25. Januar 2022, 20:21:50 CET schrieb sadashivmadiwalar:

Hi sadashivmadiwalar,

> Hi smueller,
> 
> There is high usage of CPU when using latest jitterentropy-rngd-1.2.6 over
> MIPS64 arch.
> 
> Is it expected or any possible solution? Below is log for the same.
> 
> root     24042  7.8  0.0   3328  2368 ?        Ss   08:19  10:38
> jitterentropy-rngd -p /var/run/jitterentropy-rngd.pid
> 
> strace shown lot of request for the given pid.
> 
> strace64 -s 200 -p 24042
> .....
> clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440336696}) = 0
> clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440425432}) = 0
> clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440514256}) = 0
> clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440603112}) = 0
> clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440691876}) = 0
> clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440781104}) = 0
> clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440870384}) = 0
> clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=440962468}) = 0
> clock_gettime(CLOCK_REALTIME, {tv_sec=1643128758, tv_nsec=441052004}) = 0
> ....
> 
> Kernel Version is : 3.10.59
> Arch is: Netlogic XLP700/900 Series.

Can you please check when invoking the rngd with -vvv whether (a) many logs 
are generated which means that somehow the entropy is not properly added to 
the kernel or (b) only a few log entries appear and then a huge CPU usage 
appears. In the latter case this means that somehow the entropy gathering 
logic is stuck.

Thanks
Stephan
> 
> Thanks,
> Sadashiv


Ciao
Stephan

**Comment by sadashivmadiwalar** [comment]
Hi Stephan,
Below is the rngd with -vvv.

jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install termination signal handler
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Sufficient entropy 3193 available
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Sufficient entropy 3200 available
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Sufficient entropy 3781 available
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for select on /dev/random
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Sufficient ^C
jitterentropy-rngd - Debug: Shutting down cleanly

It is generating continuous log.

How to get this resolved?
Thanks,
Sadashiv

**Comment by smuellerDD** [comment]
Am Donnerstag, 3. Februar 2022, 09:29:09 CET schrieb sadashivmadiwalar:

Hi sadashivmadiwalar,

> It is generating continuous log.

This means that the kernel continuously pings the rngd to generate data as it 
seems the entropy pool is either not filling up or there is a data hog at /
dev/random pulling large mounts of data.
> 
> How to get this resolved?

You are saying this happens with a 3.10 kernel?

While that high CPU usage is ongoing, can you please invoke the following 
multiple times:

cat /proc/sys/kernel/random/entropy_avail

And can you please check you system whether you have an entropy hog somewhere? 
Maybe stop your user space as much as possible, terminate all daemons etc. and 
see whether the issue persists.

> Thanks,
> Sadashiv


Ciao
Stephan

**Comment by sadashivmadiwalar** [comment]
Hi Stephen,
I collected entropy_avail using cat command. Below is the result.
/proc # ps -aux | grep rngd
Warning: bad ps syntax, perhaps a bogus '-'? See http://procps.sf.net/faq.html
root     63750 47.9  0.0   3328  2240 ?        Ss   21:10   0:21 /mswitch/bin/jitterentropy-rngd
root     71649  0.0  0.0   3712  1408 ttyS0    S+   21:11   0:00 grep rngd
/proc # cat /proc/sys/kernel/random/entropy_avail
3079
/proc # cat /proc/sys/kernel/random/entropy_avail
2954
/proc # cat /proc/sys/kernel/random/entropy_avail
3090
/proc # cat /proc/sys/kernel/random/entropy_avail
2965
/proc # cat /proc/sys/kernel/random/entropy_avail
3095
/proc # cat /proc/sys/kernel/random/entropy_avail
2970

To be precise I wrote python script to read this entropy_avail that gave entropy_avail more than write_wakeup_threshold, below is the result
/flash/debug_rngd # python read_entropy.py
3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

3171

Seems that no other process/demon is consuming entropies but below is the ps command result and strace which is consuming more CPU even though sufficient entropy_avail are there.
/flash/debug_rngd # ps -aux | grep rngd
Warning: bad ps syntax, perhaps a bogus '-'? See http://procps.sf.net/faq.html
root     63750 **27.0**  0.0   3328  2240 ?        Rs   21:10   2:42 /mswitch/bin/jitterentropy-rngd
root     78017  0.0  0.0   3712  1408 ttyS0    S+   21:20   0:00 grep rngd

/flash/debug_rngd # strace64 -p 63750
strace64: Process 63750 attached
_newselect(31, NULL, [30], NULL, NULL)  = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL} ---
read(31, "3106\n", 5)                   = 5
lseek(31, 0, SEEK_SET)                  = 0
rt_sigaction(SIGALRM, {sa_handler=0x10008de0, sa_mask=[RT_37 RT_42 RT_45 RT_47 RT_48 RT_49 RT_50 RT_52 RT_53 RT_54 RT_58 RT_59 RT_60 RT_62 RT_63 RT_64 RT_65 RT_66 RT_67 RT_68 RT_69 RT_70 RT_71 RT_72], sa_flags=SA_RESTART}, {sa_handler=0x10008de0, sa_mask=[], sa_flags=SA_RESTART}, 16) = 0
alarm(5)                                = 0
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
_newselect(31, NULL, [30], NULL, NULL)  = 1 (out [30])
rt_sigprocmask(SIG_BLOCK, [ALRM], [], 16) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643952078, tv_nsec=721881040}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643952078, tv_nsec=722050520}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643952078, tv_nsec=722285476}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643952078, tv_nsec=722594540}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643952078, tv_nsec=722754736}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643952078, tv_nsec=722932324}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643952078, tv_nsec=723075188}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643952078, tv_nsec=723233128}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643952078, tv_nsec=723365184}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643952078, tv_nsec=723542164}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1643952078, tv_nsec=723755448}) = 0

What could be the other reason that this jitter entropy is taking more CPU time?

Thanks,
Sadashiv

**Comment by dermotbradley** [comment]
@smuellerDD Could this mips64 problem be the same sort of issue I (and some others) had with rng-tools/jitterentropy on the Raspberry PI which was addressed by tweaking (in that case) the rngd configuration to reduce buffer_size, refill_thresh, and thread_count?

**Comment by sadashivmadiwalar** [comment]
Hi @smuellerDD and @dermotbradley,

Any possible solution to this problem?

@dermotbradley 
Can you please share the tweaking or workarounds you did on Raspberry PI?

Thanks,
Sadashiv

**Comment by smuellerDD** [comment]
Am Donnerstag, 24. März 2022, 13:26:25 CET schrieb sadashivmadiwalar:

Hi sadashivmadiwalar,

> Hi @smuellerDD and @dermotbradley,
> 
> Any possible solution to this problem?
> 
> @dermotbradley
> Can you please share the tweaking or workarounds you did on Raspberry PI?

Sorry, not yet, but working on it.
> 
> Thanks,
> Sadashiv


Ciao
Stephan

**Comment by sadashivmadiwalar** [comment]
Hi Stephan,
I tried few workaround. But found that kernel always let jitter poll write avalibe, see driver/char/random.c. So I tried commenting out below init sequence within file rng-tools-4/rngd_linux.c  and init_kernel_rng function.

diff --git a/utils/rng-tools-4/rngd_linux.c b/utils/rng-tools-4/rngd_linux.c
index 46db9510ca..5157af4638 100644
--- a/utils/rng-tools-4/rngd_linux.c
+++ b/utils/rng-tools-4/rngd_linux.c
@@ -102,7 +102,7 @@ void init_kernel_rng(const char* randomdev)
+#if !defined(MIPS_XLP_PLATFORM)
        f = fopen("/proc/sys/kernel/random/write_wakeup_threshold", "w");
        if (!f) {
                err = 1;
@@ -116,6 +116,7 @@ void init_kernel_rng(const char* randomdev)
                        "unable to adjust write_wakeup_threshold: %s",
                        strerror(errno));
        }
+#endif

This significantly reduced the usage of CPU from previous case. Mostly this may address my case for temporarily but not able to determine how this reduced the CPU usage. Below random kernel entropy status most of the time.

/tmp # ps -aux | grep rngd
Warning: bad ps syntax, perhaps a bogus '-'? See http://procps.sf.net/faq.html
root      2193  0.0  0.0   2560  1792 ?        S    00:08   0:00 /usr/sbin/rngd --no-drng=1 --foreground
root      2196  2.3  0.0   3328  2560 ?        S    00:08   0:02 /mswitch/bin/jitterentropy-rngd -n -p /var/run/jitterentropy-rngd.pid >> $bootlog
root      4438  0.0  0.0   3712  1408 ttyS0    S+   00:10   0:00 grep rngd
/tmp #
/tmp # cat /proc/sys/kernel/random/write_wakeup_threshold
128
/tmp # cat /proc/sys/kernel/random/entropy_avail
276
/tmp # cat /proc/sys/kernel/random/poolsize
4096
/tmp # cat /proc/sys/kernel/random/read_wakeup_threshold
64
/tmp #
/tmp # cat /proc/sys/kernel/random/entropy_avail
307
/tmp # cat /proc/sys/kernel/random/entropy_avail
181
/tmp # cat /proc/sys/kernel/random/entropy_avail
129
/tmp # cat /proc/sys/kernel/random/entropy_avail
131
/tmp # cat /proc/sys/kernel/random/entropy_avail
135
/tmp # cat /proc/sys/kernel/random/entropy_avail
138
/tmp # cat /proc/sys/kernel/random/entropy_avail
266
/tmp # cat /proc/sys/kernel/random/entropy_avail
160

Even though CPU usage reduced still strace64 shows lot of request to kernel and Below is the jitter result with verbose option:
/tmp # /mswitch/bin/jitterentropy-rngd -vvvv
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install termination signal handler
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 451 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 160 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 174 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 193 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 467 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 160 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random
jitterentropy-rngd - Verbose: Wakeup call for alarm on /proc/sys/kernel/random/entropy_avail
jitterentropy-rngd - Debug: Insufficient entropy 175 available
jitterentropy-rngd - Debug: Injected 64 bytes with an entropy count of 32 bytes of entropy
jitterentropy-rngd - Verbose: 64 bytes written to /dev/random
jitterentropy-rngd - Debug: Install alarm signal handler
jitterentropy-rngd - Debug: Polling /dev/random

Can we consider this as temporary fix or is this reveal something we can tweak futher?

Thanks,
Sadashiv

**Comment by dermotbradley** [comment]
> Hi @smuellerDD and @dermotbradley,
> 
> @dermotbradley Can you please share the tweaking or workarounds you did on Raspberry PI?

As mentioned in https://github.com/nhorman/rng-tools/issues/150 I configured rngd as follows:

buffer_size:4133 refill_thresh:4133 thread_count:1

This ensured that only a single core would be used.

I don't know how/if a similar configuration could be made with jitterentropy-rngd.

**Comment by smuellerDD** [comment]
Am Freitag, 15. April 2022, 03:03:32 CEST schrieb dermotbradley:

Hi dermotbradley,

> > Hi @smuellerDD and @dermotbradley,
> > 
> > @dermotbradley Can you please share the tweaking or workarounds you did on
> > Raspberry PI?
> As mentioned in https://github.com/nhorman/rng-tools/issues/150 I configured
> rngd as follows:
> 
> buffer_size:4133 refill_thresh:4133 thread_count:1
> 
> This ensured that only a single core would be used.
> 
> I don't know how/if a similar configuration could be made with
> jitterentropy-rngd.

Apologies for the delay in answering.

I now see that the issues you are having is more with the rng-tools than with 
the library itself. I was looking through my code and performed some tests and 
all seemed to work.

@nhorman, may I ask you to have a short look at this threat? It seems that 
something is related to the rngd.

Thanks a lot.

Ciao
Stephan

**Comment by nhorman** [comment]
I'm.....extremely confused by what's going on here.  It seems like @sadashivmadiwalar is reporting a problem with jitterentropy-rngd regarding high CPU usage on mips, and @dermotbradley chimed in referencing our discussion of his issues with rng_tools, which we resolved with a bit of tuning.  Regarding his comment that @sadashivmadiwalar's issue is the same, I'm really not sure, it looks like maybe jiterretnropy-rngd is getting stuck calling clock_gettime repeatedly, which IIRC is usually a symptom of the clock time granularity being too coarse (though again, not sure)

**Comment by smuellerDD** [comment]
Am Freitag, 22. April 2022, 22:04:38 CEST schrieb Neil Horman:

Hi Neil,

> I'm.....extremely confused by what's going on here.  It seems like
> @sadashivmadiwalar is reporting a problem with jitterentropy-rngd regarding
> high CPU usage on mips, and @dermotbradley chimed in referencing our
> discussion of his issues with rng_tools, which we resolved with a bit of
> tuning.  Regarding his comment that @sadashivmadiwalar's issue is the same,
> I'm really not sure, it looks like maybe jiterretnropy-rngd is getting
> stuck calling clock_gettime repeatedly, which IIRC is usually a symptom of
> the clock time granularity being too coarse (though again, not sure)

Thanks for the clarification. @sadashivmadiwalar could you please confirm 
whether your issue is with the jitterentropy-rngd? 

Ciao
Stephan

**Comment by dermotbradley** [comment]
I'm also confused as well.

@smuellerDD I am not having **any** problems with jitterentropy-rngd (nor with rng-tools either for that matter). @sadashivmadiwalar is the person having a jitterentropy-rngd problem.

@smuellerDD @nhorman I pointed out my previous rng-tools issue to highlight how the tuning of rngd (reducing cores used to a single core etc) addressed an issue of high CPU usage on a low-end CPU (various Raspberry Pis with between 1 and 4 cores) and was suggesting to the person to check if perhaps jitterentropy-rngd provided a *similar* way to tune things.

**Comment by smuellerDD** [comment]
Am Samstag, 23. April 2022, 02:48:45 CEST schrieb dermotbradley:

Hi dermotbradley,

> I'm also confused as well.
> 
> @smuellerDD I am not having **any** problems with jitterentropy-rngd (nor
> with rng-tools either for that matter). @sadashivmadiwalar is the person
> having a jitterentropy-rngd problem.
> 
> @smuellerDD @nhorman I pointed out my previous rng-tools issue to highlight
> how the tuning of rngd (reducing cores used to a single core etc) addressed
> an issue of high CPU usage on a low-end CPU (various Raspberry Pis with
> between 1 and 4 cores) and was suggesting to the person to check if perhaps
> jitterentropy-rngd provided a *similar* way to tune things.

Thanks a lot for the confirmation. 

@sadashivmadiwalar could you please provide some details about your setup and 
the CPU - e.g. /proc/cpuinfo?

Ciao
Stephan

**Comment by sadashivmadiwalar** [comment]
Hi @smuellerDD
Please find the below /proc/cpuinfo. There are total 16 CPU threads(For
simplicity I have copied first two and last one for reference).
/tmp # cat /proc/cpuinfo
system type             : Broadcom XLPII Series [Id 15 Rev 3]
machine                 : netlogic,XLP-GVP
processor               : 0
cpu model               : Broadcom XLPII V0.3  FPU V0.3 @ 1600MHz
BogoMIPS                : 1600.00
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 544
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 1, address/irw mask: [0x0fff]
isa                     : mips1 mips2 mips3 mips4 mips5 mips32r1 mips32r2
mips64r1 mips64r2
ASEs implemented        : vz
shadow register sets    : 1
kscratch registers      : 4
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : Broadcom XLPII V0.3  FPU V0.3 @ 1600MHz
BogoMIPS                : 1600.00
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 544
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 1, address/irw mask: [0x0fff]
isa                     : mips1 mips2 mips3 mips4 mips5 mips32r1 mips32r2
mips64r1 mips64r2
ASEs implemented        : vz
shadow register sets    : 1
kscratch registers      : 4
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
.....
.....
processor               : 15
cpu model               : Broadcom XLPII V0.3  FPU V0.3 @ 1600MHz
BogoMIPS                : 1600.00
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 544
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 1, address/irw mask: [0x0fff]
isa                     : mips1 mips2 mips3 mips4 mips5 mips32r1 mips32r2
mips64r1 mips64r2
ASEs implemented        : vz
shadow register sets    : 1
kscratch registers      : 4
package                 : 0
core                    : 3
VCED exceptions         : not available
VCEI exceptions         : not available

Thanks,
Sadashiv

**Comment by sadashivmadiwalar** [comment]
Hi @smuellerDD 
Any update on this?
Thanks,
Sadashiv

**Comment by smuellerDD** [comment]
Am Freitag, 20. Mai 2022, 09:10:57 CEST schrieb sadashivmadiwalar:

Hi sadashivmadiwalar,

> Hi @smuellerDD
> Any update on this?

Apologies, I plan to get to it this weekend. The other developments held me 
back.


> Thanks,
> Sadashiv


Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Montag, 25. April 2022, 08:40:31 CEST schrieb sadashivmadiwalar:

Hi sadashivmadiwalar,

Apologies for the delay.

Have you tried the internal timer? Considering that you have a number of CPUs, 
you could replace the external with the internal timer as sometimes the 
external timers on small systems are not high-resolution or are borderline for 
the Jitter RNG.

Invoke the rngd with --flags 8 (this forces the JENT_FORCE_INTERNAL_TIMER 
flag).

Ciao
Stephan

**Comment by smuellerDD** [comment]
Closing issue due to no answer. If the issue persists, please reopen.
