### ISSUE TITLE
Compiling Jitterentropy library as 32 bit

### ISSUE THREAD

**Issue by PeterAdamson** [smuellerDD/jitterentropy-library#85]
Hello,

Is it possible to compile/build the Jitterentropy library as 32 bit rather than 64 bit?

I am trying to link jitter into a crypto library, but the crypto library requires the -m32 flag when compiling, which results in the compiler skipping my built libjitterentropy.a, as it is incompatible.

Thanks

**Comment by smuellerDD** [comment]
Am Mittwoch, 9. Februar 2022, 13:58:39 CET schrieb PeterAdamson:

Hi PeterAdamson,

> Hello,
> 
> Is it possible to compile the Jitterentropy library as 32 bit rather than 64
> bit?

Sure, I see no problem in that. When I add -m32 to the CFLAGS and LDFLAGS, I 
get the following on my 64 bit system:

$ file libjitterentropy.so.3.4.0
libjitterentropy.so.3.4.0: ELF 32-bit LSB shared object, Intel 80386, version 
1 (SYSV), dynamically linked, 
BuildID[sha1]=9591806fc38aef95eb182267c66445813b679ec8, not stripped
> 
> I am trying to link jitter into a crypto library, but the crypto library
> requires the -m32 flag when compiling, which results in the compiler
> skipping my built libjitterentropy.a, as it is incompatible.
> 

Can you

> Thanks


Ciao
Stephan

**Comment by PeterAdamson** [comment]
Thanks Stephan, I'm not super familiar with C compilation, so this helped.  Much appreciated
