### ISSUE TITLE
Help request:  Jitterentropy draining entropy on repeated calls

### ISSUE THREAD

**Issue by PeterAdamson** [smuellerDD/jitterentropy-library#87]
Hello,

I am trying to link jitter into an existing crypto library, and have been successful in modifying the TRNG to use jitter on the back end.  However, I am running into an issue where the default behavior of the crypto library is to generate a single byte at a time.  This results in a huge number of repeated calls to the generator (e.g. for 256 bytes there will be 256 separate calls to the TRNG). 

Regardless of feelings towards how this TRNG is handled, I am somewhat locked in to that behavior, as that is what the entire library is already built around.  The issue I am running into is that as a result of this, I am encountering errors surrounding lack of entropy when linking this TRNG with Jitter.

Is there any way that you could think of for me to modify how Jitter behaves to work around this entropy draining scenario?

Apologies in advance for the relatively high level general question.

**Comment by PeterAdamson** [comment]
Nevermind, We were able to modify the one byte at a time behavior.

**Comment by smuellerDD** [comment]
Am Mittwoch, 6. April 2022, 13:43:42 CEST schrieb PeterAdamson:

Hi PeterAdamson,

> Nevermind, We were able to modify the one byte at a time behavior.

Great. The Jitter RNG generates data in 256 bit chunks. Any requests other 
than this block size will be supplied, but the most efficient implementation 
is the use of 256 bit blocks.

Ciao
Stephan
