### ISSUE TITLE
`jent_loop_shuffle` is broken when `JENT_CONF_DISABLE_LOOP_SHUFFLE` is not defined

### ISSUE THREAD

**Issue by joshuaehill** [smuellerDD/jitterentropy-library#91]
https://github.com/smuellerDD/jitterentropy-library/blob/c6adeee6a1550b7454cf2d05274c61f5f9ad09d3/src/jitterentropy-noise.c#L52-L64

In `jent_loop_shuffle`, the `time` is never set to a non-zero value, so the resulting `shuffle` is always zero after this loop.

Additionally, it isn't really clear to me why the loop counter involves `DATA_SIZE_BITS` (here 256 bits), when the underlying time type is 64 bits long. This essentially causes the last few iterations of the loop to do nothing to shuffle, even if the `time` is properly initialized.

**Comment by smuellerDD** [comment]
Fixed, thanks.
