### ISSUE TITLE
OpenSSL replacements inside jent_zalloc() and jent_zfree()

### ISSUE THREAD

**Issue by gideonda1** [smuellerDD/jitterentropy-library#96]
Why do jent_zalloc() and jent_zfree() use OpenSSL function calls instead of standard library calls if the OPENSSL macro is defined?

1. For a user of jitterentropy-library who is seeking FIPS 800-90B certification, does it make any difference whether this macro is defined or not (from the assessor's point of view)?
2. Is it implied that the OPENSSL_*() calls are more 'secure' somehow and should be preferred to be used?

I've read the presentation [What to Expect When You're Expecting](https://www.untruth.org/~josh/sp80090b/What%20To%20Expect%20When%20You're%20Expecting%20(to%20Evaluate%20JEnt%20Against%20SP%20800-90B)%2020210904-1.pdf) from Joshua Hill about getting the jitterentropy-library assessed against 800-90B.  That was a really good read.  I didn't see anything about these memory alloc/free replacements within that document though.

In the version of OpenSSL we are using, OPENSSL_malloc() and OPENSSL_free() end up being wrappers around vanilla malloc() and free() with these trivial(?) differences:

 1. A counter to keep track of active mallocs;
 4. An optional hook to a third-party implementation of malloc() (**which we don't use**); and
 5. An optional switch for memory (leak?) debugging (**which we don't use**).

OPENSSL_cleanse() looks like an architecture-specific assembly-language equivalent of a memset() to all zeroes.  I guess the only reason they would do this is to avoid these calls getting optimized away by the compiler?

If I'm not mistaken, recent versions of jitterentropy-library turn compiler optimization off with -O0, so a call to cleanse() shouldn't make much difference either.

If someone could clarify the reasoning behind the OPENSSL_* calls from an 800-90B assessment point of view, that would be really nice.

**Comment by smuellerDD** [comment]
Am Freitag, 10. März 2023, 03:06:53 CET schrieb gideonda1:

Hi gideonda1,

> Why do jent_zalloc() and jent_zfree() use OpenSSL function calls instead of
> standard library calls if the OPENSSL macro is defined?

Because this macro is only defined if compiled together with OpenSSL to be 
integrated into it instead of a separate shared library.
> 
> 1. For a user of jitterentropy-library who is seeking FIPS 800-90B
> certification, does it make any difference whether this macro is defined or
> not (from the assessor's point of view)? 2. Is it implied that the
> OPENSSL_*() calls are more 'secure' somehow and should be preferred to be
> used?

Correct - but this is not the motivation of the code.
> 
> I've read the presentation [What to Expect When You're
> Expecting](https://www.untruth.org/~josh/sp80090b/What%20To%20Expect%20When
> %20You're%20Expecting%20(to%20Evaluate%20JEnt%20Against%20SP%20800-90B)%2020
> 210904-1.pdf) from Joshua Hill about getting the jitterentropy-library
> assessed against 800-90B.  That was a really good read.  I didn't see
> anything about these memory alloc/free replacements within that document
> though.
> 
> In the version of OpenSSL we are using, OPENSSL_malloc() and OPENSSL_free()
> end up being wrappers around vanilla malloc() and free() with these
> trivial(?) differences:
> 
>  1. A counter to keep track of active mallocs;
>  4. An optional hook to a third-party implementation of malloc() (**which we
> don't use**); and 5. An optional switch for memory (leak?) debugging
> (**which we don't use**).
> 
> OPENSSL_cleanse() looks like an architecture-specific assembly-language
> equivalent of a memset() to all zeroes.  I guess the only reason they would
> do this is to avoid these calls getting optimized away by the compiler?
> 
> If I'm not mistaken, recent versions of jitterentropy-library turn compiler
> optimization off with -O0, so a call to cleanse() shouldn't make much
> difference either.


Ciao
Stephan

**Comment by gideonda1** [comment]
Thanks for your prompt reply.

> Because this macro is only defined if compiled together with OpenSSL to be integrated into it instead of a separate shared library.

So if I understand correctly; if we have no intention of _integrating_ this library into OpenSSL, there's no need to have the OPENSSL macro defined, is that correct?

**Comment by smuellerDD** [comment]
Am Dienstag, 14. März 2023, 00:24:16 CET schrieb gideonda1:

Hi gideonda1,

> Thanks for your prompt reply.
> 
> > Because this macro is only defined if compiled together with OpenSSL to be
> > integrated into it instead of a separate shared library.
> So if I understand correctly; if we have no intention of _integrating_ this
> library into OpenSSL, there's no need to have the OPENSSL macro defined, is
> that correct?

Correct.

Ciao
Stephan
